plugins {
    `kotlin-dsl`
    `maven-publish`
}

group = "io.github.thisisthepy"
version = "3.13.0" // kept in step with the root build's version, which the processor is published under

dependencies {
    // The plugin applies KSP itself, so the KSP Gradle plugin has to be on its runtime classpath
    // -- but deliberately *not* on its compile classpath.
    //
    // `kotlin-dsl` compiles against Gradle's embedded Kotlin (2.0.20 on Gradle 8.11.1; it was 1.9
    // on the 8.9 this build used before ROADMAP §13), and KSP 2.3.11 is compiled with Kotlin 2.3:
    // "Class 'com.google.devtools.ksp.gradle.KspExtension' was compiled with an incompatible
    // version of Kotlin ... the compiler version 1.9.0 can read versions up to 2.0.0". The
    // Gradle bump narrowed that gap but did not close it -- 2.0.20 reads up to 2.1 -- so
    // `runtimeOnly` still applies. It keeps the id resolvable (plugin ids are resolved from a
    // classpath resource, not from compiled types) while the two `ksp { arg(...) }` calls go
    // through `PythonBindingsPlugin.setKspArg`.
    runtimeOnly("com.google.devtools.ksp:symbol-processing-gradle-plugin:${libs.versions.ksp.get()}")
    testImplementation(kotlin("test"))
}

gradlePlugin {
    plugins {
        create("pythonMultiplatformBindings") {
            id = "io.github.thisisthepy.python.multiplatform.bindings"
            implementationClass = "python.multiplatform.gradle.PythonBindingsPlugin"
            displayName = "Python Multiplatform bindings"
            description = "Wires the python-multiplatform KSP processor into every Kotlin target of a module."
        }
    }
}

/**
 * The default processor coordinates have to name this build's own group and version, and a
 * hand-copied string would drift the first time either changes. Generating a one-line source file
 * keeps it derived.
 */
val generateCoordinates = tasks.register("generateCoordinates") {
    val outputDir = layout.buildDirectory.dir("generated/coordinates")
    // Plain `group`/`version` here resolve against the task itself (`Task.getGroup()` is a task
    // category label, always null on this task; `Task` has no `version` property so that one
    // falls through to the project by luck) -- not against the project, even though this lambda
    // reads as if it were project-scoped. Qualifying both is what makes the generated coordinates
    // name this build's actual group instead of the literal string "null".
    val coordinates = "${project.group}:python-multiplatform-ksp:${project.version}"
    inputs.property("coordinates", coordinates)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("python/multiplatform/gradle/ProcessorCoordinates.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            // GENERATED by the plugin build. Do not edit.
            package python.multiplatform.gradle

            internal const val DEFAULT_PROCESSOR_COORDINATES: String = "$coordinates"
            """.trimIndent() + "\n",
        )
    }
}

sourceSets.main {
    kotlin.srcDir(generateCoordinates)
}

tasks.test {
    useJUnitPlatform()
}
