package python.multiplatform.ksp

private const val FRAGMENT_INTERFACE = "python.multiplatform.reflection.FunctionTableFragment"
private const val EXPOSED_CALLABLE = "python.multiplatform.reflection.ExposedCallable"
private const val REFLECTED_CLASS = "python.multiplatform.reflection.ReflectedClass"
private const val TYPE_TAG = "python.multiplatform.reflection.TypeTag"
private const val CALLABLE_KIND = "python.multiplatform.reflection.CallableKind"
private const val REFLECTED_CLASS_KIND = "python.multiplatform.reflection.ReflectedClassKind"

private fun String.quoted(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""

private fun renderEntry(entry: CallableEntryModel): String {
    val paramTags = entry.paramTags.joinToString(", ") { "$TYPE_TAG.$it" }
    // Omitted rather than rendered as `false`: the runtime default already says so, and every
    // entry in every fragment would otherwise carry a line that means nothing.
    val suspendArg = if (entry.isSuspend) "\n|    isSuspend = true," else ""
    return """
        |$EXPOSED_CALLABLE(
        |    name = ${entry.name.quoted()},
        |    arity = ${entry.arity},
        |    paramTypes = listOf($paramTags),
        |    returnType = $TYPE_TAG.${entry.returnTag},
        |    kind = $CALLABLE_KIND.${entry.kind},$suspendArg
        |    callable = ${entry.lambdaBody},
        |)
    """.trimMargin()
}

private fun renderClass(cls: ClassModel): String {
    val members = cls.memberNames.joinToString(", ") { it.quoted() }
    val traverseArg = if (cls.traverseBody != null) ",\n    traverse = ${cls.traverseBody}" else ""
    val entryNamesArg = if (cls.enumEntryNames.isEmpty()) {
        ""
    } else {
        ",\n    enumEntryNames = listOf(${cls.enumEntryNames.joinToString(", ") { it.quoted() }})"
    }
    return """
        |$REFLECTED_CLASS(
        |    name = ${cls.name.quoted()},
        |    memberNames = listOf($members),
        |    kind = $REFLECTED_CLASS_KIND.${cls.kind}$entryNamesArg$traverseArg,
        |)
    """.trimMargin()
}

/**
 * Renders one `Fragment_<module>.kt` file body -- what a library-role KSP invocation emits.
 *
 * The object is `public` rather than `internal` as `docs/upcall-table-design.md`'s sketch shows
 * it: `internal` is enforced per Kotlin *module*, and the app module compiling generated source
 * that references a library's fragment is a different module by that rule even inside the same
 * Gradle build. An `internal` fragment fails to compile from the app side with "cannot access
 * ... it is internal in ...". Nothing about the design needs the fragment hidden from Python --
 * it is reached only by name, through [python.multiplatform.reflection.UpcallTable] -- so the
 * relaxation costs nothing.
 */
fun renderFragmentSource(model: FragmentModel): String {
    val objectName = fragmentObjectName(model.moduleName)
    val entries = model.entries.joinToString(",\n") { renderEntry(it).prependIndent("        ") }
    val classes = model.classes.joinToString(",\n") { renderClass(it).prependIndent("        ") }
    return buildString {
        // Every argument read is `args[i] as SomeType` out of an `Array<Any?>`, which is
        // unchecked whenever the type has type arguments (`List<String>`). Suppressing at file
        // level rather than per cast keeps the generated source readable and the build quiet.
        appendLine("@file:Suppress(\"UNCHECKED_CAST\")")
        appendLine()
        appendLine("// GENERATED by python-multiplatform-ksp. Do not edit.")
        appendLine("package $FRAGMENTS_PACKAGE")
        appendLine()
        if (model.classes.any { it.traverseBody != null }) {
            // `.pointer.toRawValue()` in a generated traverse body resolves through this import
            // rather than a fully-qualified call, to keep the rendered lambda readable.
            appendLine("import python.native.ffi.toRawValue")
            appendLine()
        }
        appendLine("object $objectName : $FRAGMENT_INTERFACE {")
        appendLine("    override val moduleName: String = ${model.moduleName.quoted()}")
        appendLine()
        appendLine("    override fun entries(): List<$EXPOSED_CALLABLE> = listOf(")
        if (entries.isNotEmpty()) appendLine(entries)
        appendLine("    )")
        appendLine()
        appendLine("    override fun classes(): List<$REFLECTED_CLASS> = listOf(")
        if (classes.isNotEmpty()) appendLine(classes)
        appendLine("    )")
        appendLine("}")
    }
}

/**
 * Renders `FunctionTable.kt` -- the app-role aggregator. [fragmentQualifiedNames] is the result
 * of fragment discovery (`docs/upcall-table-design.md` §2): every `Fragment_*` object this app
 * module and its dependencies emitted, found via
 * [FragmentDiscovery][python.multiplatform.ksp.FragmentDiscovery] and referenced here
 * explicitly. That explicit reference is what keeps every fragment reachable to the Kotlin/Native
 * linker with no `ServiceLoader` and no `@EagerInitialization`.
 */
fun renderAggregatorSource(fragmentQualifiedNames: List<String>): String = buildString {
    appendLine("// GENERATED by python-multiplatform-ksp. Do not edit.")
    appendLine("package $AGGREGATOR_PACKAGE")
    appendLine()
    appendLine("object FunctionTable {")
    appendLine("    /** Every fragment this module can see: itself, plus every dependency that")
    appendLine("     * carries one. Referencing them here -- rather than letting each fragment")
    appendLine("     * register itself -- is what makes them reachable without a ServiceLoader.")
    appendLine("     */")
    appendLine("    val fragments: List<$FRAGMENT_INTERFACE> = listOf(")
    fragmentQualifiedNames.forEach { appendLine("        $it,") }
    appendLine("    )")
    appendLine()
    appendLine("    /** Convenience for the common case: replace whatever")
    appendLine("     * [python.multiplatform.reflection.UpcallTable] currently holds with exactly")
    appendLine("     * this module graph's fragments. */")
    appendLine("    fun installInto() {")
    appendLine("        python.multiplatform.reflection.UpcallTable.install(fragments)")
    appendLine("    }")
    appendLine("}")
}
