plugins {
    alias(libs.plugins.kotlin.jvm)
    `maven-publish`
}

kotlin {
    jvmToolchain(17)
}

dependencies {
    implementation("com.google.devtools.ksp:symbol-processing-api:${libs.versions.ksp.get()}")
    testImplementation(libs.kotlin.test)
    testImplementation(libs.kotlin.test.junit)
}

tasks.test {
    useJUnit()
}

// Without this, DEFAULT_PROCESSOR_COORDINATES (generated by
// python-multiplatform-gradle-plugin's `generateCoordinates` task, from this same group/artifactId/
// version) names an artifact that never gets published anywhere -- every consumer outside this repo
// resolves the plugin id fine and then fails on the processor dependency itself.
publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
        }
    }
}
