package python.multiplatform.gradle.artifact

import kotlin.test.Test
import kotlin.test.assertEquals

/**
 * Where the walker's output joins KSP's, and why it is a second list rather than a longer first one.
 *
 * `docs/ecosystem.md` §5b: both producers run at build time under the same applied plugin, and both
 * emit `FunctionTableFragment`s into the one `UpcallTable`. The question this pins is only *who
 * assembles the list*.
 *
 * KSP's `FunctionTable` is not extended, for three reasons:
 *
 * 1. **`FunctionTable` already means something.** `PackageScanFragmentDiscovery` builds it from
 *    `Resolver.getDeclarationsFromPackage(python.multiplatform.generated.fragments)` -- "every
 *    module in this graph that was compiled with the processor". `ksp-fixtures/app`'s
 *    `CommonInstallTest` asserts that set exactly. Putting walked artefacts in it would silently
 *    change a shipped contract, and would make a consumer's table grow when they added an unrelated
 *    dependency.
 * 2. **The ordering would have to be built the wrong way round.** For KSP to *see* a walked
 *    fragment, the walker's source would have to be generated before `kspKotlin<Target>` runs and
 *    land somewhere `getDeclarationsFromPackage` looks. That API's behaviour for declarations that
 *    exist only in the source being processed is undocumented; a fragment it silently missed would
 *    disappear from the table with no build failure anywhere. Emitting a list the walker owns
 *    outright removes the question.
 * 3. **Which artefacts to bind is a consumer's decision, and should be visible at the install
 *    site.** Nobody wants every declaration on their compile classpath in their Python namespace.
 *
 * So: one `UpcallTable`, one fragment interface, one Python surface -- two aggregators, named after
 * the two things they aggregate.
 */
class ArtifactTableRenderingTest {

    @Test
    fun theAggregatorAddsRatherThanReplaces() {
        val source = renderArtifactTableSource(listOf("ArtifactFragment_a", "ArtifactFragment_b"))
        assertEquals(
            """
            |// GENERATED by python-multiplatform-gradle-plugin. Do not edit.
            |package python.multiplatform.generated.artifacts
            |
            |/**
            | * Every resolved artefact this module asked to have bound.
            | *
            | * Not merged into `python.multiplatform.generated.FunctionTable`: that one means "every
            | * module in this build graph that was compiled with the processor", and a walked
            | * third-party jar is not one. Install both:
            | *
            | *     UpcallTable.install(FunctionTable.fragments + ArtifactTable.fragments)
            | */
            |object ArtifactTable {
            |    val fragments: List<python.multiplatform.reflection.FunctionTableFragment> = listOf(
            |        ArtifactFragment_a,
            |        ArtifactFragment_b,
            |    )
            |
            |    /** Adds these to whatever is already installed, leaving it in place. */
            |    fun registerInto() {
            |        fragments.forEach { python.multiplatform.reflection.UpcallTable.register(it) }
            |    }
            |}
            |
            """.trimMargin(),
            source,
        )
    }

    /**
     * A coordinate is not an identifier, and a fragment object's name has to be one.
     *
     * The same sanitisation `python-multiplatform-ksp`'s `sanitiseModuleName` does for a Gradle path,
     * applied to what a resolved artefact calls itself. The *module* name keeps the original text,
     * because `UpcallTable.register` deduplicates on it and two coordinates that differ only in
     * punctuation must not collapse into one.
     */
    @Test
    fun coordinatesBecomeIdentifiers() {
        assertEquals("ArtifactFragment_junit_junit_4_13_2", artifactFragmentObjectName("junit:junit:4.13.2"))
        assertEquals(
            "ArtifactFragment_org_jetbrains_kotlin_kotlin_stdlib_2_4_20_Beta2",
            artifactFragmentObjectName("org.jetbrains.kotlin:kotlin-stdlib:2.4.20-Beta2"),
        )
        assertEquals("ArtifactFragment_project__lib", artifactFragmentObjectName("project :lib"))
    }
}
