package python.multiplatform.gradle.artifact

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

/**
 * The text the walker writes, pinned.
 *
 * The shape is `python-multiplatform-ksp`'s `renderFragmentSource` on purpose: the same
 * `FunctionTableFragment`, the same `ExposedCallable`, the same one-lambda-per-entry body. The two
 * producers differ in what they read, not in what they emit -- so the runtime, `UpcallTable` and
 * `PythonProxySource` all stay unaware that there are two of them. See
 * [ArtifactTableRenderingTest.theAggregatorAddsRatherThanReplaces] for the one place they are kept
 * apart, and why.
 */
class ArtifactFragmentRenderingTest {

    private val versionId = ArtifactCallable(
        name = "junit.runner.Version.id",
        arity = 0,
        paramTags = emptyList(),
        returnTag = "STRING",
        lambdaBody = "{ (junit.runner.Version.id()) }",
    )

    private val setPreference = ArtifactCallable(
        name = "junit.runner.BaseTestRunner.setPreference",
        arity = 2,
        paramTags = listOf("STRING", "STRING"),
        returnTag = "UNIT",
        lambdaBody = "{ args -> (junit.runner.BaseTestRunner.setPreference((args[0] as String), (args[1] as String))) }",
        paramTypeNames = listOf("kotlin.String", "kotlin.String"),
        returnTypeName = "kotlin.Unit",
    )

    /** An extension, so that the rendered `isExtension`/`receiverTypeName` pair -- the fields
     * `docs/pythonx-adapter-design.md` §4.2 needs and §2.4 records as lost -- appears in the pinned
     * text rather than only in a scanner unit test. */
    private val trimIndent = ArtifactCallable(
        name = "kotlin.text.trimIndent",
        arity = 1,
        paramTags = listOf("STRING"),
        returnTag = "STRING",
        lambdaBody = "{ args -> ((args[0] as String).artifact_ext_kotlin_text_trimIndent()) }",
        imports = listOf("import kotlin.text.trimIndent as artifact_ext_kotlin_text_trimIndent"),
        receiverTypeName = "kotlin.String",
        paramNames = listOf("<receiver>"),
        paramTypeNames = listOf("kotlin.String"),
        returnTypeName = "kotlin.String",
        paramHasDefault = listOf(false),
    )

    @Test
    fun aFragmentIsTheSameShapeKspEmits() {
        val source = renderArtifactFragmentSource(
            ArtifactFragment(
                objectName = "ArtifactFragment_junit_junit_4_13_2",
                moduleName = "artifact:junit:junit:4.13.2",
                entries = listOf(versionId, setPreference, trimIndent),
            ),
        )
        assertEquals(
            """
            |// GENERATED by python-multiplatform-gradle-plugin. Do not edit.
            |@file:Suppress("UNCHECKED_CAST", "DEPRECATION", "DEPRECATION_ERROR", "OPT_IN_USAGE", "OPT_IN_USAGE_ERROR")
            |
            |package python.multiplatform.generated.artifacts
            |
            |import kotlin.text.trimIndent as artifact_ext_kotlin_text_trimIndent
            |
            |object ArtifactFragment_junit_junit_4_13_2 : python.multiplatform.reflection.FunctionTableFragment {
            |    override val moduleName: String = "artifact:junit:junit:4.13.2"
            |
            |    override fun entries(): List<python.multiplatform.reflection.ExposedCallable> = listOf(
            |        python.multiplatform.reflection.ExposedCallable(
            |            name = "junit.runner.Version.id",
            |            arity = 0,
            |            paramTypes = listOf(),
            |            returnType = python.multiplatform.reflection.TypeTag.STRING,
            |            kind = python.multiplatform.reflection.CallableKind.FUNCTION,
            |            paramNames = listOf(),
            |            paramTypeNames = listOf(),
            |            returnTypeName = null,
            |            isExtension = false,
            |            receiverTypeName = null,
            |            paramHasDefault = listOf(),
            |            callable = { (junit.runner.Version.id()) },
            |        ),
            |        python.multiplatform.reflection.ExposedCallable(
            |            name = "junit.runner.BaseTestRunner.setPreference",
            |            arity = 2,
            |            paramTypes = listOf(python.multiplatform.reflection.TypeTag.STRING, python.multiplatform.reflection.TypeTag.STRING),
            |            returnType = python.multiplatform.reflection.TypeTag.UNIT,
            |            kind = python.multiplatform.reflection.CallableKind.FUNCTION,
            |            paramNames = listOf(),
            |            paramTypeNames = listOf("kotlin.String", "kotlin.String"),
            |            returnTypeName = "kotlin.Unit",
            |            isExtension = false,
            |            receiverTypeName = null,
            |            paramHasDefault = listOf(),
            |            callable = { args -> (junit.runner.BaseTestRunner.setPreference((args[0] as String), (args[1] as String))) },
            |        ),
            |        python.multiplatform.reflection.ExposedCallable(
            |            name = "kotlin.text.trimIndent",
            |            arity = 1,
            |            paramTypes = listOf(python.multiplatform.reflection.TypeTag.STRING),
            |            returnType = python.multiplatform.reflection.TypeTag.STRING,
            |            kind = python.multiplatform.reflection.CallableKind.FUNCTION,
            |            paramNames = listOf("<receiver>"),
            |            paramTypeNames = listOf("kotlin.String"),
            |            returnTypeName = "kotlin.String",
            |            isExtension = true,
            |            receiverTypeName = "kotlin.String",
            |            paramHasDefault = listOf(false),
            |            callable = { args -> ((args[0] as String).artifact_ext_kotlin_text_trimIndent()) },
            |        ),
            |    )
            |}
            |
            """.trimMargin(),
            source,
        )
    }

    /**
     * A fragment with nothing in it still renders valid Kotlin.
     *
     * `PythonArtifactBindingsTask` does not *emit* one -- an artefact that contributed nothing gets
     * no file and no line in `ArtifactTable`, because an empty fragment would still occupy a
     * `moduleName` in `UpcallTable`'s installed set, which is the one thing that set is read for.
     * The renderer is kept total anyway so that "which artefacts get a file" stays the task's
     * decision, changeable without a second empty-list bug in the text.
     */
    @Test
    fun anEmptyFragmentIsStillAFragment() {
        val source = renderArtifactFragmentSource(
            ArtifactFragment("ArtifactFragment_x", "artifact:x", emptyList()),
        )
        assertTrue(source.contains("override fun entries(): List<python.multiplatform.reflection.ExposedCallable> = listOf(\n    )"))
    }

    /**
     * `DEPRECATION` is suppressed because a walked artefact is not the consumer's code: JUnit 4's
     * own `junit.framework.Assert` is deprecated, and a consumer who asked for a binding should not
     * be handed a warning about a declaration they did not write.
     *
     * `OPT_IN_USAGE_ERROR` is the same argument at Compose's scale: `@ExperimentalFoundationApi` and
     * its siblings are `RequiresOptIn` at ERROR level, so `Modifier.combinedClickable` would fail a
     * consumer's *compile* rather than warn. The marker cannot be known here -- any library may
     * invent one -- so the diagnostic is suppressed rather than an `@OptIn` guessed at.
     */
    @Test
    fun somebodyElsesCompilerDiagnosticsAreSuppressedInGeneratedSource() {
        val source = renderArtifactFragmentSource(ArtifactFragment("ArtifactFragment_x", "artifact:x", listOf(versionId)))
        assertTrue(source.contains("\"DEPRECATION_ERROR\""), source)
        assertTrue(source.contains("\"OPT_IN_USAGE_ERROR\""), source)
    }
}
