package python.multiplatform.gradle

import org.gradle.api.DefaultTask
import org.gradle.api.file.DirectoryProperty
import org.gradle.api.provider.Property
import org.gradle.api.tasks.Input
import org.gradle.api.tasks.OutputDirectory
import org.gradle.api.tasks.TaskAction

/**
 * Generates the three `@WasmExport` trampoline functions that CPython's type-slot machinery
 * calls back through into Kotlin.
 *
 * ### Why this task exists
 *
 * `@WasmExport` is honoured only in the compilation that produces the `.wasm` binary. A library
 * klib linked in does not propagate its `@WasmExport` declarations into the binary's export
 * section -- measured, not assumed: the identical annotation on the identical function exported
 * from `wasmJsTest` and did not export from `wasmJsMain` (see `ProxyTypeExportNames`'s KDoc).
 *
 * So the three trampoline functions must be declared in every executable (or test-binary)
 * compilation that embeds this library. Previously they lived as hand-written boilerplate in
 * `wasmJsTest/kotlin/.../ProxyTypeExports.kt`; this task generates the equivalent file so that
 * no embedding module needs to copy three lines and understand why they exist.
 *
 * ### What it generates
 *
 * ```kotlin
 * // GENERATED by python-multiplatform-gradle-plugin. Do not edit.
 * @file:OptIn(kotlin.wasm.ExperimentalWasmInterop::class)
 * package <packageName>
 *
 * @kotlin.wasm.WasmExport("pmp_tp_traverse")
 * fun pmpTpTraverse(selfPtr: Int, visitPtr: Int, argPtr: Int): Int =
 *     python.multiplatform.ffi.ProxyType.traverse(selfPtr, visitPtr, argPtr)
 *
 * @kotlin.wasm.WasmExport("pmp_tp_clear")
 * fun pmpTpClear(selfPtr: Int): Int = python.multiplatform.ffi.ProxyType.clear(selfPtr)
 *
 * @kotlin.wasm.WasmExport("pmp_tp_dealloc")
 * fun pmpTpDealloc(selfPtr: Int) = python.multiplatform.ffi.ProxyType.dealloc(selfPtr)
 * ```
 *
 * ### Mirroring the install-seam pattern
 *
 * `python-multiplatform-ksp`'s `InstallSeam.kt` generates `installGeneratedUpcallTable`'s
 * `actual` into each leaf (executable) compilation -- the only place that can name `FunctionTable`.
 * This task follows exactly the same pattern: it generates into the executable's source set, the
 * one place `@WasmExport` is honoured. The package name defaults to one that keeps the file out
 * of the user's own namespace.
 */
abstract class GenerateWasmProxyExportsTask : DefaultTask() {

    /**
     * The Kotlin package the generated file is placed in.
     *
     * Defaults to `python.multiplatform.generated.wasm` -- the same `generated` prefix the KSP
     * processor uses for its own output, so the file is easy to identify as machine-produced.
     * A consumer may override it, but has no reason to: the three functions have no API surface.
     */
    @get:Input
    abstract val packageName: Property<String>

    /** Where the generated `.kt` file is written. Add this to the target source set's `kotlin.srcDir`. */
    @get:OutputDirectory
    abstract val outputDirectory: DirectoryProperty

    @TaskAction
    fun generate() {
        val pkg = packageName.get()
        val dir = outputDirectory.get().asFile
        // Package hierarchy as a directory path
        val pkgDir = pkg.split('.').fold(dir) { acc, segment -> acc.resolve(segment) }
        pkgDir.mkdirs()
        val outFile = pkgDir.resolve("$WASM_PROXY_EXPORTS_FILE_NAME.kt")
        outFile.writeText(renderWasmProxyExportsSource(pkg))
        logger.info("Generated $outFile")
    }
}
