package python.multiplatform.gradle

/**
 * Export names matching `python.multiplatform.ffi.ProxyTypeExportNames` in the library.
 *
 * Duplicated rather than imported: the Gradle plugin has no runtime dependency on
 * `python-multiplatform`, so it cannot reach the library's constants at build time.
 * These are ABI -- CPython's slot mechanism depends on them -- and they will not change
 * without a coordinated update to both the library and this plugin.
 */
internal const val WASM_EXPORT_TRAVERSE = "pmp_tp_traverse"
internal const val WASM_EXPORT_CLEAR    = "pmp_tp_clear"
internal const val WASM_EXPORT_DEALLOC  = "pmp_tp_dealloc"

/** Fully-qualified name of the library singleton that holds the slot implementations. */
private const val PROXY_TYPE = "python.multiplatform.ffi.ProxyType"

/**
 * The generated file name (no `.kt` extension; KSP/Gradle conventions omit it).
 *
 * Placed beside the other generated wasm files; the name makes its origin unambiguous.
 */
internal const val WASM_PROXY_EXPORTS_FILE_NAME = "WasmProxyTypeExports"

/**
 * Renders the three `@WasmExport` trampoline functions an executable wasm module must declare
 * so that CPython's type machinery can call back into Kotlin.
 *
 * ### Why this must be generated into the executable, not the library
 *
 * `@WasmExport` is honoured only in the compilation that produces the `.wasm` binary. A library
 * klib linked in does not carry the annotation into the binary's export section — measured, not
 * assumed: the identical annotation on the identical function exported from `wasmJsTest` and did
 * not export from `wasmJsMain`. So the three lines cannot live in the library; they must be
 * emitted into each executable compilation that embeds it.
 *
 * ### What each trampoline does
 *
 * Each body is a one-line delegation to [ProxyType]'s corresponding method. All logic, including
 * everything that could ever need changing, stays in the library. The trampolines are glue only.
 *
 * ### Arities are load-bearing
 *
 * `call_indirect` is statically typed and does not coerce. A trampoline whose arity does not
 * exactly match the C slot signature it fills raises `RuntimeError: null function or function
 * signature mismatch` at runtime. The three C signatures are:
 *
 *     int  tp_traverse(PyObject *self, visitproc visit, void *arg)  — (i32,i32,i32) -> i32
 *     int  tp_clear   (PyObject *self)                              — (i32)         -> i32
 *     void tp_dealloc (PyObject *self)                              — (i32)         -> ()
 *
 * [packageName] is the package the generated file is placed in, matching the executable module's
 * choice. It is the only variable part of the output.
 */
internal data class WasmExportSlot(
    val exportName: String,
    val kotlinName: String,
    val parameters: String,
    val returnType: String,
    val delegateCall: String,
    val multiline: Boolean = false
)

internal val DEFAULT_PROXY_TYPE_SLOTS = listOf(
    WasmExportSlot(
        exportName = WASM_EXPORT_TRAVERSE,
        kotlinName = "pmpTpTraverse",
        parameters = "selfPtr: Int, visitPtr: Int, argPtr: Int",
        returnType = "Int",
        delegateCall = "$PROXY_TYPE.traverse(selfPtr, visitPtr, argPtr)",
        multiline = true
    ),
    WasmExportSlot(
        exportName = WASM_EXPORT_CLEAR,
        kotlinName = "pmpTpClear",
        parameters = "selfPtr: Int",
        returnType = "Int",
        delegateCall = "$PROXY_TYPE.clear(selfPtr)",
        multiline = false
    ),
    WasmExportSlot(
        exportName = WASM_EXPORT_DEALLOC,
        kotlinName = "pmpTpDealloc",
        parameters = "selfPtr: Int",
        returnType = "Unit",
        delegateCall = "$PROXY_TYPE.dealloc(selfPtr)",
        multiline = false
    )
)

internal fun renderWasmProxyExportsSource(
    packageName: String,
    slots: List<WasmExportSlot> = DEFAULT_PROXY_TYPE_SLOTS
): String = buildString {
    appendLine("// GENERATED by python-multiplatform-gradle-plugin. Do not edit.")
    appendLine("// See python.multiplatform.ffi.ProxyTypeExportNames for the contract this implements.")
    appendLine("@file:OptIn(kotlin.wasm.ExperimentalWasmInterop::class)")
    appendLine()
    appendLine("package $packageName")

    for (slot in slots) {
        appendLine()
        appendLine("@kotlin.wasm.WasmExport(\"${slot.exportName}\")")
        val decl = if (slot.returnType == "Unit") {
            "fun ${slot.kotlinName}(${slot.parameters})"
        } else {
            "fun ${slot.kotlinName}(${slot.parameters}): ${slot.returnType}"
        }
        if (slot.multiline) {
            appendLine("$decl =")
            appendLine("    ${slot.delegateCall}")
        } else {
            appendLine("$decl = ${slot.delegateCall}")
        }
    }
}
