package fixture.compose

import androidx.compose.runtime.currentComposer
import androidx.compose.runtime.remember
import androidx.compose.ui.Modifier
import androidx.compose.ui.composed
import python.multiplatform.ffi.PyObject
import python.multiplatform.ffi.Python3
import python.multiplatform.ffi.types.basic.PyInt
import python.multiplatform.reflection.HandleTable
import python.native.ffi.PyLong_AsLongLong

/**
 * `Modifier.composed` -- `docs/pythonx-adapter-design.md` §9.2/§9.4's open question, now answered:
 * **a composer is admitted.** `factory`'s compiled shape is `Function3<Modifier, Composer, Integer,
 * Modifier>` (confirmed by `javap -p` on `androidx.compose.ui.ComposedModifierKt`, matching the
 * lowered shape `PythonCallables` already crosses for every composable `content=` slot), and unlike
 * `pythonLayoutIdProbe`'s dead end, `composed` itself is **not** `@Composable` -- `javap` shows no
 * synthetic `$composer`/`$changed` on the `composed` static method -- so `BindingPolicy.isComposable`
 * (which excludes only a declaration *itself* annotated `@Composable`) never sees it and does not
 * exclude it. That much was inferable from the bytecode alone; what it left open is whether the
 * composer `factory` receives, once Compose actually calls it, is the real thing wired into a live
 * slot table or a placeholder that merely satisfies the type. [ComposedInvocationSlot] is the answer:
 * a genuine [remember] inside the lambda `composed` is given persists across recompositions of the
 * *same* node -- a fake composer could not make that true (`remember`'s own implementation would
 * either throw against a non-functional `Composer` or hand back a fresh value every time, since it
 * has no slot table to remember into) -- see `ComposedRenderTest
 * .theSameCompositionReusesTheRememberedSlotAcrossRecompositions` for the measurement.
 *
 * ### The shape of the fix, and how it differs from [pythonPointerInput]
 *
 * Both are hand-written, ordinarily-compiled Kotlin bound by KSP as a plain top-level function
 * (`fixture.compose.pythonComposed`), not through the artefact walker or `pythonx`'s dynamic loader --
 * the same reasoning [pythonPointerInput]'s KDoc gives for why a plain parameter, not an extension
 * receiver, and why KSP rather than the walker. What differs is *why* a hand-written wrapper is
 * needed at all: `pointerInput`'s block is a `suspend` lambda no Python callable can itself suspend
 * as, so the fix hides a `suspend` state machine inside ordinary Kotlin. `composed`'s `factory` is not
 * suspend -- it is a lowered composable lambda, exactly what `PythonCallables` already builds crossing
 * wrappers for -- but nothing autogenerated can supply the **call site**: `composed`'s factory is
 * invoked later, by Compose's own `materialize()`, not by generated fragment code the way a `content=`
 * argument is invoked by the composable it was passed to. This function *is* that call site, written
 * once, the same role [PythonComposition] plays for the one hand-written `@Composable` entry point.
 *
 * ### Why the crossing is hand-written rather than routed through [python.multiplatform.ffi.pythonx.PythonCallables]
 *
 * `PythonCallables.PythonFunction.invoke` always discards the Python callable's return value (built
 * for `content=` slots, which are `Function3<..., Unit>`); `composed`'s factory returns a `Modifier`,
 * so its wrapper cannot reuse that path unchanged. Rather than widen a table entry point three call
 * sites do not need, this calls [factory] directly (`PyObject.invoke`, the same downcall
 * [pythonPointerInput] and [pythonDraggable] already use for a synchronous callback) and reads the
 * `Modifier` back off the returned proxy's `_pm_handle` attribute -- the same attribute
 * `PythonxAdapter`'s `_proxy_type` stores it under for every `TypeTag.OBJECT` result.
 *
 * ### The composer, and the receiver, cross the same way [PythonComposition]'s does
 *
 * [currentComposer] is rooted and pushed onto `pythonx`'s composer stack (`pythonx.push_composer`) for
 * the duration of the call, so [factory] may itself call a bound composable (the same contract
 * [PythonComposition] documents). `this` -- the `Modifier` chain [factory] receives as its receiver,
 * matching `@Composable Modifier.() -> Modifier` -- is rooted too and passed as a bare handle
 * (`int`), which `PythonxAdapter._coerce`'s OBJECT branch already accepts as a caller-selected
 * argument; a real caller threads it into e.g. `size__Dp(receiver, 70.0)` the same way any other
 * walked declaration chains a `Modifier`.
 *
 * ### What is deliberately not solved
 *
 * [factory]'s one Python reference (`UpcallTrampoline.toKotlinObject`'s fresh reference, taken once
 * when Python calls [pythonComposed]) is captured by the closure and never released -- there is no
 * `RememberObserver` hook here the way `content=`'s [python.multiplatform.ffi.pythonx.PythonCallableScope]
 * has one, and building one for a single captured `PyObject` was judged out of scope for answering
 * §9.2's question. This is [pythonDraggable]'s already-documented shape: "measured, not guessed" --
 * one reference, leaked for the modifier's lifetime, bounded because [pythonComposed] is called once
 * per modifier chain built.
 */
fun pythonComposed(modifier: Modifier, factory: PyObject): Modifier = modifier.composed {
    val slot = remember { ComposedInvocationSlot().also { ComposedInvocationSlot.remembersAllocated++ } }
    slot.invocations++
    ComposedInvocationSlot.lastCreated = slot

    val composer = currentComposer
    val composerRef = HandleTable.register(composer)
    val receiverRef = HandleTable.register(this)
    try {
        Python3.exec("import pythonx\npythonx.push_composer(${composerRef.raw})")
        try {
            val receiverHandle = PyInt.from(receiverRef.raw)
            try {
                val result = factory(receiverHandle)
                try {
                    // A proxy (`_proxy_type`'s `_pm_handle`) is the ordinary case -- `factory`
                    // returned something a walked declaration produced, e.g. `size__Dp(receiver,
                    // 70.0)`. A bare `int` is `_coerce`'s other accepted OBJECT spelling: `factory`
                    // handed the receiver handle straight back (an identity factory), which never
                    // passed through `_proxy_type` to grow a `_pm_handle` attribute.
                    val attr = result.getAttrOrNull("_pm_handle")
                    val raw = if (attr != null) {
                        try {
                            Python3.withPython { PyLong_AsLongLong(attr.pointer) }
                        } finally {
                            attr.close()
                        }
                    } else {
                        Python3.withPython { PyLong_AsLongLong(result.pointer) }
                    }
                    (HandleTable.resolveRaw(raw) as? Modifier) ?: this
                } finally {
                    result.close()
                }
            } finally {
                receiverHandle.close()
            }
        } finally {
            Python3.exec("import pythonx\npythonx.pop_composer()")
        }
    } finally {
        HandleTable.release(receiverRef)
        HandleTable.release(composerRef)
    }
}

/**
 * Test-visible evidence that [remember] inside [pythonComposed]'s `composed { }` lambda holds a real
 * slot, not a value recreated on every call.
 *
 * [invocations] is a per-instance counter, bumped on every call of the lambda regardless of whether
 * `remember` allocated a new [ComposedInvocationSlot] or handed back an old one -- so it tells apart
 * "the lambda ran N times" from "the lambda's remembered state was recreated N times", which
 * [remembersAllocated] (bumped only inside `remember`'s factory) answers instead. A composer wired
 * into a real composition makes [remembersAllocated] stay `1` across many recompositions of the same
 * node while [invocations] keeps climbing; a placeholder composer that could not support `remember`
 * would either crash or make the two track each other.
 */
class ComposedInvocationSlot {
    var invocations: Int = 0

    companion object {
        var remembersAllocated: Int = 0
        var lastCreated: ComposedInvocationSlot? = null

        fun reset() {
            remembersAllocated = 0
            lastCreated = null
        }
    }
}
