package org.thisisthepy.python.multiplatform.demo.bindings

import python.multiplatform.ffi.Python3
import python.multiplatform.generated.FunctionTable
import python.multiplatform.reflection.UpcallTable
import python.native.ffi.UpcallStub

/** `Py_eval_input`: compile an expression rather than a sequence of statements. */
private const val PY_EVAL_INPUT: Int = 258

/**
 * `FunctionTable` is generated by `python-multiplatform-ksp` into this target's compilation. It
 * exists because `build.gradle.kts` applies the bindings plugin, and for no other reason.
 */
actual fun installGeneratedUpcallTable() {
    UpcallTable.install(FunctionTable.fragments)
    installCtypesBridge()
}

/**
 * Resolve once, invoke many. `_pm_handle` is computed here and lives on in `__main__`, so every
 * call afterwards passes an integer and never a string again -- which is the whole argument of
 * `docs/upcall-design.md` (a selector is fast because it is interned, not because a table
 * exists).
 *
 * `ctypes` stands in for the generated proxy type a finished binder would install. Both stub
 * addresses are Panama upcall stubs of shape `(long) -> long`, which is why the entry this demo
 * calls takes no arguments and returns a `Long`.
 */
private fun installCtypesBridge() {
    val resolveAddr = UpcallStub.resolveHandleStubAddr
    val invokeAddr = UpcallStub.invokeHandleStubAddr
    Python3.exec(
        """
        import ctypes

        _pm_resolve = ctypes.CFUNCTYPE(ctypes.c_long, ctypes.c_char_p)($resolveAddr)
        _pm_invoke = ctypes.CFUNCTYPE(ctypes.c_long, ctypes.c_long)($invokeAddr)
        _pm_handle = _pm_resolve(b"$UPCALL_ENTRY_NAME")
        """.trimIndent(),
    )
}

actual fun callKotlinFromPython(): String = try {
    val globals = Python3.import("__main__").dict
    val handle = Python3.eval("_pm_handle", PY_EVAL_INPUT, globals, globals).toString()
    if (handle == "-1") {
        "the name was not in the table (handle -1)"
    } else {
        val value = Python3.eval("_pm_invoke(_pm_handle)", PY_EVAL_INPUT, globals, globals)
        "Python called Kotlin through handle $handle and got $value"
    }
} catch (t: Throwable) {
    "${t::class.simpleName}: ${t.message}"
}
