package python.multiplatform.gradle.artifact

/** The package walked artefacts' fragments land in. Deliberately **not**
 * `python.multiplatform.generated.fragments`, which `PackageScanFragmentDiscovery` sweeps into
 * KSP's `FunctionTable` -- see [renderArtifactTableSource]. It is still under
 * `python.multiplatform.generated`, which `python-multiplatform-ksp`'s
 * `ALWAYS_EXCLUDED_PACKAGE_PREFIXES` excludes by prefix, so the processor never rescans this
 * generated source as if a consumer had written it. */
internal const val ARTIFACTS_PACKAGE = "python.multiplatform.generated.artifacts"

private const val FRAGMENT_INTERFACE = "python.multiplatform.reflection.FunctionTableFragment"
private const val EXPOSED_CALLABLE = "python.multiplatform.reflection.ExposedCallable"
private const val TYPE_TAG = "python.multiplatform.reflection.TypeTag"
private const val CALLABLE_KIND = "python.multiplatform.reflection.CallableKind"
private const val UPCALL_TABLE = "python.multiplatform.reflection.UpcallTable"

/**
 * One binding taken out of a compiled artefact.
 *
 * Mirrors `python.multiplatform.ksp.CallableEntryModel` field for field, minus what a jar cannot
 * answer: there is no `isSuspend` (a `suspend` function's JVM shape takes a `Continuation`, which
 * [boundaryTypeOf] declines, so no suspending declaration ever reaches here) and no `kind` (every
 * entry is a `FUNCTION`, because only statics are bound -- an instance method would need a
 * `ReflectedClass` and a receiver handle, which is the next step and not this one).
 */
internal data class ArtifactCallable(
    val name: String,
    val arity: Int,
    val paramTags: List<String>,
    val returnTag: String,
    val lambdaBody: String,
)

/** One artefact's worth of bindings: what becomes a single `FunctionTableFragment` object. */
internal data class ArtifactFragment(
    val objectName: String,
    val moduleName: String,
    val entries: List<ArtifactCallable>,
)

private fun String.quoted(): String = "\"" + replace("\\", "\\\\").replace("\"", "\\\"") + "\""

/**
 * A Kotlin identifier for a resolved artefact's coordinates.
 *
 * `python.multiplatform.ksp.sanitiseModuleName`'s rule, widened: a `ComponentIdentifier`'s display
 * name is `group:name:version` for a module and `project :path` for a project, so spaces and colons
 * have to go the way periods and hyphens do.
 */
internal fun artifactFragmentObjectName(coordinates: String): String =
    "ArtifactFragment_" + coordinates.map { if (it.isLetterOrDigit()) it else '_' }.joinToString("")

private fun renderEntry(entry: ArtifactCallable): String {
    val paramTags = entry.paramTags.joinToString(", ") { "$TYPE_TAG.$it" }
    return """
        |$EXPOSED_CALLABLE(
        |    name = ${entry.name.quoted()},
        |    arity = ${entry.arity},
        |    paramTypes = listOf($paramTags),
        |    returnType = $TYPE_TAG.${entry.returnTag},
        |    kind = $CALLABLE_KIND.FUNCTION,
        |    callable = ${entry.lambdaBody},
        |)
    """.trimMargin()
}

/**
 * Renders one artefact's fragment.
 *
 * The same file shape `python-multiplatform-ksp`'s `renderFragmentSource` emits, because the
 * runtime must not be able to tell the two producers apart: `UpcallTable`, `CallableHandle` and
 * `PythonProxySource` all see a `FunctionTableFragment` and nothing more.
 *
 * `DEPRECATION` joins `UNCHECKED_CAST` in the file-level suppression for a reason KSP's version does
 * not have: the declarations here are somebody else's. JUnit 4's own `junit.framework.Assert` is
 * deprecated, and a consumer who asked for a binding should not be handed a warning about source
 * they did not write and cannot change.
 */
internal fun renderArtifactFragmentSource(fragment: ArtifactFragment): String = buildString {
    appendLine("// GENERATED by python-multiplatform-gradle-plugin. Do not edit.")
    appendLine("@file:Suppress(\"UNCHECKED_CAST\", \"DEPRECATION\", \"DEPRECATION_ERROR\")")
    appendLine()
    appendLine("package $ARTIFACTS_PACKAGE")
    appendLine()
    appendLine("object ${fragment.objectName} : $FRAGMENT_INTERFACE {")
    appendLine("    override val moduleName: String = ${fragment.moduleName.quoted()}")
    appendLine()
    appendLine("    override fun entries(): List<$EXPOSED_CALLABLE> = listOf(")
    fragment.entries.forEach { appendLine(renderEntry(it).prependIndent("        ") + ",") }
    appendLine("    )")
    appendLine("}")
}

/**
 * Renders the aggregator over every walked artefact.
 *
 * A second list beside KSP's `FunctionTable` rather than an extension of it. The reasoning is in
 * `ArtifactTableRenderingTest`'s class doc, and the short form is in the generated doc comment
 * below so that a reader who only ever sees the output gets it too.
 */
internal fun renderArtifactTableSource(fragmentObjectNames: List<String>): String = buildString {
    appendLine("// GENERATED by python-multiplatform-gradle-plugin. Do not edit.")
    appendLine("package $ARTIFACTS_PACKAGE")
    appendLine()
    appendLine("/**")
    appendLine(" * Every resolved artefact this module asked to have bound.")
    appendLine(" *")
    appendLine(" * Not merged into `python.multiplatform.generated.FunctionTable`: that one means \"every")
    appendLine(" * module in this build graph that was compiled with the processor\", and a walked")
    appendLine(" * third-party jar is not one. Install both:")
    appendLine(" *")
    appendLine(" *     UpcallTable.install(FunctionTable.fragments + ArtifactTable.fragments)")
    appendLine(" */")
    appendLine("object ArtifactTable {")
    appendLine("    val fragments: List<$FRAGMENT_INTERFACE> = listOf(")
    fragmentObjectNames.forEach { appendLine("        $it,") }
    appendLine("    )")
    appendLine()
    appendLine("    /** Adds these to whatever is already installed, leaving it in place. */")
    appendLine("    fun registerInto() {")
    appendLine("        fragments.forEach { $UPCALL_TABLE.register(it) }")
    appendLine("    }")
    appendLine("}")
}
