package python.multiplatform.gradle.stubs

import python.multiplatform.gradle.model.DeclarationModel
import python.multiplatform.gradle.model.DeclaredParameter

/**
 * `docs/pyi-generation-design.md` §5.3's two stub products, rendered from one model.
 *
 * | product | namespace | what it describes |
 * |---|---|---|
 * | [renderKotlinFqnStubs] | `androidx.compose.foundation.layout`, `junit.runner.Version` | the modules `PythonProxySource` injects into `sys.modules` **today** |
 * | [renderPythonicStubs] | `pythonx.compose.layout` | what a user imports |
 *
 * Both return *relative path to file content*, so nothing here touches a disk and every assertion in
 * `PyiRenderingTest` is over text. `PythonStubsTask` is the only thing that writes.
 */

private const val HEADER = "# GENERATED by python-multiplatform-gradle-plugin. Do not edit."

/**
 * The 1:1 product: one `def` per `UpcallTable` key, in the module the runtime publishes it onto.
 *
 * ### The types are the boundary's, not the declaration's
 *
 * `PythonProxySource.renderOne` publishes `setattr(_pm_module('androidx.compose.foundation.layout'),
 * 'padding__Dp', f)` where `f` is `def _pm_f_7(a0, a1)`, and `UpcallTrampoline` marshals a `Dp`
 * argument as a raw float and a `Modifier` return as a `HandleTable` integer. So this product
 * annotates `float` and `int`: that is what the module accepts and returns, and
 * `docs/pyi-generation-design.md` §7 lists the handle-to-proxy wrapping that would make it
 * `Modifier` as *not yet done*. Saying `-> Modifier` here would be the exact lie that section warns
 * about. The Kotlin signature goes in the docstring, which is where a reader wants it and where no
 * checker can act on it.
 *
 * ### Positional-only
 *
 * The runtime function's parameters are named `a0, a1, ...` -- `PythonProxySource.params`. A stub
 * promising `padding__Dp(all=16)` would type-check and then raise `TypeError`. The Kotlin names are
 * still emitted, because an editor shows them, and the trailing `/` makes them non-binding. This is
 * §3.2's spelling applied for a second, independent reason: there it is a Java jar with no names,
 * here it is a runtime that renames.
 */
internal fun renderKotlinFqnStubs(declarations: List<DeclarationModel>): Map<String, String> {
    val byModule = declarations
        .filter { it.bindingName != null && !it.isSuspend }
        .groupBy { it.bindingName!!.substringBeforeLast('.') }
    return byModule.toSortedMap().mapValues { (_, entries) ->
        buildString {
            appendLine(HEADER)
            appendLine()
            entries.sortedBy { it.bindingName }.forEach { declaration ->
                appendLine(renderKotlinFqnDef(declaration))
                appendLine()
            }
        }
    }.mapKeys { (module, _) -> module.replace('.', '/') + "/__init__.pyi" }
}

private fun renderKotlinFqnDef(declaration: DeclarationModel): String {
    val leaf = declaration.bindingName!!.substringAfterLast('.')
    val parameters = mutableListOf<String>()
    // The extension receiver is the runtime's `a0`; naming it after the receiver's Kotlin type would
    // suggest a keyword that does not exist, so it gets one fixed positional name.
    if (declaration.receiver != null) parameters += "receiver: " + boundaryAnnotation(declaration.receiverBoundaryTag)
    declaration.parameters.forEachIndexed { index, parameter ->
        val name = if (declaration.parameterNamesKnown) parameter.name ?: "__a$index" else "__a$index"
        parameters += "$name: " + boundaryAnnotation(parameter.boundaryTag)
    }
    val signature = if (parameters.isEmpty()) "()" else "(${parameters.joinToString(", ")}, /)"
    return buildString {
        appendLine("def $leaf$signature -> ${boundaryAnnotation(declaration.returnBoundaryTag)}:")
        appendLine("    \"\"\"Kotlin: ${kotlinSignatureOf(declaration)}\"\"\"")
        append("    ...")
    }
}

/**
 * `python.multiplatform.reflection.TypeTag` to the Python type that actually crosses.
 *
 * `OBJECT` is `int` because it is: `UpcallTrampoline.marshalResult` puts the Kotlin object in
 * `HandleTable` and hands Python the resulting integer, and `PythonProxySource`'s KDoc records that
 * such a handle "is the caller's to release".
 */
private fun boundaryAnnotation(tag: String?): String = when (tag) {
    "INT", "OBJECT" -> "int"
    "FLOAT" -> "float"
    "BOOLEAN" -> "bool"
    "STRING" -> "str"
    "BYTES" -> "bytes"
    "UNIT" -> "None"
    else -> "object"
}

/** What the docstring says: the declaration as Kotlin wrote it, which is the information the
 * annotations above deliberately do not carry. */
private fun kotlinSignatureOf(declaration: DeclarationModel): String {
    val owner = declaration.receiver?.qualifiedName ?: declaration.owner
    val parameters = declaration.parameters.joinToString(", ") { parameter ->
        val type = parameter.type.qualifiedName + if (parameter.type.isNullable) "?" else ""
        if (declaration.parameterNamesKnown && parameter.name != null) "${parameter.name}: $type" else type
    }
    return "$owner.${declaration.simpleName}($parameters): ${declaration.returnType.qualifiedName}"
}

// --------------------------------------------------------------------------- the Pythonic product

/**
 * The product a user imports: `docs/pyi-generation-design.md` §4.4's callback-Protocol attributes,
 * §3.6's arity-ascending `@overload`s, §3.4's value-class allowlist, §3.5's keyword-only `content`,
 * and §6.1's `py.typed`.
 *
 * Empty when the manifest is: §5.3 says which Kotlin package a `pythonx` module wraps is the Python
 * package's decision and §5.2 measures that it is not inferable (`pythonx.compose.layout` drops
 * `foundation.`), so with nothing to read from, only the Kotlin-FQN product is emitted.
 *
 * **This product describes a surface that does not exist yet.** It says `-> Modifier` where the
 * runtime hands back a handle integer; §7 lists that wrapping as not done, and `pythonx`'s adapter is
 * what will do it. That is the difference between the two products and the reason there are two.
 */
internal fun renderPythonicStubs(declarations: List<DeclarationModel>, manifest: StubManifest): Map<String, String> {
    if (manifest == StubManifest.EMPTY) return emptyMap()
    val allowlist = manifest.rawPrimitiveValueClasses

    val stubbable = declarations.filter { it.bindingName != null && !it.isSuspend }
    val placed = stubbable.mapNotNull { declaration ->
        val moduleOwner = declaration.receiver?.qualifiedName?.let { packagePartOf(it) }
            ?: if (declaration.ownerIsClass) packagePartOf(declaration.owner) else declaration.owner
        val module = manifest.pythonModuleFor(moduleOwner) ?: return@mapNotNull null
        Placed(module, declaration)
    }
    if (placed.isEmpty()) return pyTypedOnly(manifest)

    // Which module owns each class name that anything refers to. A class is owned by the module its
    // own Kotlin package maps to, whether or not this build bound anything on it -- otherwise
    // `PaddingValues` would be referenced by `pythonx.compose.ui` and defined nowhere.
    val referenced = LinkedHashSet<String>()
    placed.forEach { (_, declaration) ->
        declaration.receiver?.let { referenced += it.qualifiedName }
        declaration.parameters.forEach { referenced += PythonTypes.render(it.type, allowlist).referencedClasses }
        referenced += PythonTypes.render(declaration.returnType, allowlist).referencedClasses
    }
    val classModules = referenced.mapNotNull { qualified ->
        manifest.pythonModuleFor(packagePartOf(qualified))?.let { qualified to it }
    }.toMap()

    val byModule = placed.groupBy({ it.module }, { it.declaration })
    // Every module that owns a class is rendered too, even when this build bound nothing in it: a
    // `from pythonx.compose.ui import Modifier` in another stub has to resolve, and §6.1 measurement
    // 3 is what says a stub-only tree with no `.py` beside it does.
    val modules = (byModule.keys + classModules.values).toSortedSet()
    val files = LinkedHashMap<String, String>()
    modules.forEach { module ->
        files += renderPythonicModule(
            module = module,
            declarations = byModule[module].orEmpty(),
            ownedClasses = classModules.filterValues { it == module }.keys.toSortedSet(),
            classModules = classModules,
            manifest = manifest,
        )
    }
    files += pyTypedOnly(manifest)
    return files
}

private data class Placed(val module: String, val declaration: DeclarationModel)

/**
 * The classes one module declares, keeping Kotlin's nesting.
 *
 * An enclosing class is created on the way to a nested one whether or not anything referred to it,
 * because a module-level `class Horizontal` is a different name from `Alignment.Horizontal` and
 * nothing would resolve.
 */
private class ClassNodeTree {
    private val children = sortedMapOf<String, ClassNodeTree>()
    private var attributes: List<String> = emptyList()
    private var protocolPrefix: String = ""
    private var constructors: List<String> = emptyList()

    fun put(path: List<String>, attributes: List<String>, protocolPrefix: String, constructors: List<String>) {
        if (path.isEmpty()) return
        val child = children.getOrPut(path.first()) { ClassNodeTree() }
        if (path.size == 1) {
            child.attributes = attributes
            child.protocolPrefix = protocolPrefix
            child.constructors = constructors
        } else {
            child.put(path.drop(1), attributes, protocolPrefix, constructors)
        }
    }

    fun renderInto(out: StringBuilder, indent: String) {
        children.forEach { (name, child) ->
            out.appendLine("${indent}class $name:")
            val inner = "$indent    "
            child.constructors.forEach { out.appendLine("$inner$it") }
            if (child.attributes.isEmpty() && child.children.isEmpty() && child.constructors.isEmpty()) {
                // Referred to but carrying nothing this build bound. Declared rather than left to an
                // import from nowhere: the annotation has to resolve for the stub to have any effect
                // at all (§6.1).
                out.appendLine("$inner...")
            }
            child.attributes.forEach { attribute ->
                // §4.4: `ClassVar` is not load-bearing for inference -- a plain annotation gives
                // byte-identical results -- but it is the honest one and it stops a checker accepting
                // `m.padding = something`.
                out.appendLine("$inner$attribute: ClassVar[${child.protocolPrefix}_$attribute]")
            }
            child.renderInto(out, inner)
            if (indent.isEmpty()) out.appendLine()
        }
    }
}

private fun pyTypedOnly(manifest: StubManifest): Map<String, String> {
    val root = manifest.distributionRoot ?: return emptyMap()
    return mapOf(root.replace('.', '/') + "/py.typed" to "")
}

private fun renderPythonicModule(
    module: String,
    declarations: List<DeclarationModel>,
    ownedClasses: Set<String>,
    classModules: Map<String, String>,
    manifest: StubManifest,
): Map<String, String> {
    val allowlist = manifest.rawPrimitiveValueClasses
    val typingImports = sortedSetOf<String>()
    val referencedClasses = LinkedHashSet<String>()

    // `(receiver class, python name)` -- §4.4's "one Protocol class per (receiver, name) pair", the
    // cost that section states outright: ~507 of them across corpus A, 130 for `Modifier` alone.
    val methods = declarations.filter { it.receiver != null }
        .groupBy { it.receiver!!.qualifiedName to PythonNames.functionName(it.simpleName, it.isComposable) }
    val functions = declarations.filter { it.receiver == null }
        .groupBy { PythonNames.functionName(it.simpleName, it.isComposable) }

    fun signature(declaration: DeclarationModel): String {
        val rendered = declaration.parameters.map { PythonTypes.render(it.type, allowlist) }
        rendered.forEach { typingImports += it.typingImports; referencedClasses += it.referencedClasses }
        val returned = PythonTypes.render(declaration.returnType, allowlist)
        typingImports += returned.typingImports
        referencedClasses += returned.referencedClasses
        val parts = mutableListOf<String>()
        declaration.parameters.forEachIndexed { index, parameter ->
            if (isKeywordOnly(declaration, index)) parts += "*"
            val name = PythonNames.parameterName(parameter.name ?: "a$index")
            parts += name + ": " + rendered[index].expression + if (parameter.declaresDefault) " = ..." else ""
        }
        return "(${parts.joinToString(", ")}) -> ${returned.expression}"
    }

    val body = StringBuilder()
    val protocols = StringBuilder()
    val dispatch = sortedMapOf<String, List<String>>()

    /**
     * The overloads of one name, in the order they are emitted, with the ones a checker could never
     * select removed.
     *
     * `docs/pyi-generation-design.md` §7's third open item -- "whether any real Compose overload set
     * collapses... The generator must detect that and drop or qualify, and how often it happens is
     * unknown -- it needs the scan to be run." It was run, and it does happen: mypy 2.3.0 on the
     * generated `androidx.compose.foundation.layout` stub reported
     * `WindowInsets(left: int = ..., ...)` as "signature 2 will never be matched", because the
     * `Dp | float` overload above it already accepts an `int` (a checker's numeric tower makes `int`
     * acceptable wherever `float` is). Emitting it anyway is an error in the consumer's own type
     * check, which is not something a generated stub may cost them.
     */
    fun reachableOverloads(group: List<DeclarationModel>): Pair<List<DeclarationModel>, List<DeclarationModel>> {
        val ordered = group.sortedWith(compareBy({ it.parameters.size }, { it.bindingName }))
        val kept = mutableListOf<DeclarationModel>()
        val dropped = mutableListOf<DeclarationModel>()
        ordered.forEach { candidate ->
            val shadowed = kept.any { earlier -> subsumes(earlier, candidate, allowlist) }
            if (shadowed) dropped += candidate else kept += candidate
        }
        return kept to dropped
    }

    methods.toSortedMap(compareBy({ it.first }, { it.second })).forEach { (key, group) ->
        val (receiverClass, pythonName) = key
        val (ordered, dropped) = reachableOverloads(group)
        val protocolName = "_" + pythonClassPathOf(receiverClass).replace(".", "_") + "_" + pythonName
        protocols.appendLine("class $protocolName(Protocol):")
        dropped.forEach { protocols.appendLine("    # ${unreachableNote(it)}") }
        ordered.forEach { declaration ->
            // `@overload` only for a group of more than one: mypy rejects a lone `@overload` outright
            // ("Single overload definition, multiple required"), which is an error in the *consumer's*
            // check, so the single case is a plain `def`.
            if (ordered.size > 1) protocols.appendLine("    @overload")
            val rendered = signature(declaration)
            val separator = if (declaration.parameters.isEmpty()) "" else ", "
            protocols.appendLine("    def __call__(self$separator${rendered.removePrefix("(")}: ...")
        }
        protocols.appendLine()
        dispatch["${pythonClassPathOf(receiverClass)}.$pythonName"] = ordered.map { it.bindingName!! }
    }

    // A Kotlin "fake constructor" -- a top-level function whose name is a class's, which is how
    // Compose spells `PaddingValues(16.dp)` and `WindowInsets(...)`. In Python a class *is* callable,
    // so the honest stub is `__init__` on that class; emitting a module-level `def PaddingValues`
    // beside `class PaddingValues` is a redefinition and mypy says so ("Name already defined").
    val ownedTopLevelNames = ownedClasses.associateBy { pythonClassPathOf(it) }
    val constructors = LinkedHashMap<String, List<String>>()

    functions.toSortedMap().forEach { (pythonName, group) ->
        val (ordered, dropped) = reachableOverloads(group)
        val target = ownedTopLevelNames[pythonName]
        if (target != null) {
            constructors[pythonName] = buildList {
                dropped.forEach { add("# ${unreachableNote(it)}") }
                ordered.forEach { declaration ->
                    if (ordered.size > 1) add("@overload")
                    val rendered = signature(declaration).substringBeforeLast(" -> ")
                    val separator = if (declaration.parameters.isEmpty()) "" else ", "
                    add("def __init__(self$separator${rendered.removePrefix("(")} -> None: ...")
                }
            }
        } else {
            dropped.forEach { body.appendLine("# ${unreachableNote(it)}") }
            ordered.forEach { declaration ->
                if (ordered.size > 1) body.appendLine("@overload")
                body.appendLine("def $pythonName${signature(declaration)}: ...")
            }
            body.appendLine()
        }
        dispatch[pythonName] = ordered.map { it.bindingName!! }
    }

    // Nested classes stay nested. `@Metadata` spells `Alignment.Horizontal` with a dot, so splitting
    // the qualified name on the last one made `Alignment` look like a package and produced a
    // `pythonx/compose/ui/Alignment/` directory for a class that has no module. The tree is built
    // from the class paths, with any enclosing class an owned nested class needs declared even when
    // nothing referred to the enclosing class itself.
    val tree = ClassNodeTree()
    ownedClasses.forEach { qualified ->
        val path = pythonClassPathOf(qualified)
        tree.put(
            path = path.split('.'),
            attributes = methods.keys.filter { it.first == qualified }.map { it.second }.sorted(),
            protocolPrefix = "_" + path.replace(".", "_"),
            constructors = constructors[path].orEmpty(),
        )
    }
    val classes = StringBuilder().also { tree.renderInto(it, indent = "") }

    if (protocols.isNotEmpty()) typingImports += "Protocol"
    if (methods.isNotEmpty()) typingImports += "ClassVar"
    val emitted = protocols.toString() + body.toString() + classes.toString()
    if ("@overload" in emitted) typingImports += "overload"

    val imports = classModules.entries
        .filter { (qualified, owner) -> owner != module && qualified in referencedClasses }
        // The *top-level* class is what gets imported; `Alignment.Horizontal` is reached through it.
        .groupBy({ it.value }, { pythonClassPathOf(it.key).substringBefore('.') })
        .toSortedMap()

    // A class this module refers to whose own package maps nowhere. Not silently dropped and not
    // guessed at: the annotation has to resolve for the stub to have any effect at all (§6.1), so it
    // is declared opaque here and the fact is in the comment.
    val unplaced = referencedClasses.filter { it !in classModules && it !in ownedClasses }.sorted()

    val file = buildString {
        appendLine(HEADER)
        appendLine()
        if (typingImports.isNotEmpty()) appendLine("from typing import ${typingImports.joinToString(", ")}")
        imports.forEach { (from, names) -> appendLine("from $from import ${names.sorted().distinct().joinToString(", ")}") }
        if (typingImports.isNotEmpty() || imports.isNotEmpty()) appendLine()
        unplaced.forEach { qualified ->
            appendLine("# $qualified has no Pythonic module; declared opaque so the annotation resolves.")
            appendLine("class ${pythonClassPathOf(qualified).substringBefore('.')}: ...")
            appendLine()
        }
        append(protocols)
        append(classes)
        append(body)
    }

    val path = module.replace('.', '/')
    val result = LinkedHashMap<String, String>()
    result["$path/__init__.pyi"] = file
    if (dispatch.isNotEmpty()) result["$path/_pm_dispatch.json"] = renderDispatch(dispatch)
    return result
}

/**
 * Whether [earlier] would take every call [later] could -- in which case a checker never selects
 * [later], and emitting it is an error in the consumer's own type check.
 *
 * `docs/pyi-generation-design.md` §7's third open item: "two Kotlin overloads can map to identical
 * Python signatures once `Dp | float` widening is applied. The generator must detect that and drop
 * or qualify, and how often it happens across the 33 multi-overload `Modifier` names is unknown --
 * it needs the scan to be run." It was run: mypy 2.3.0 over the generated
 * `androidx.compose.foundation.layout` stub reported exactly one, Compose's second `WindowInsets`
 * factory, whose `int` parameters are all accepted by the `Dp | float` overload above it.
 *
 * Deliberately narrow. It requires the same arity **and the same parameter names**, because a
 * keyword call can still select a later overload whose keyword only exists there. Within that, one
 * rendered type subsumes another when they are equal, when the narrower is a member of the broader
 * union, or when the broader is `float` and the narrower is `int` -- a checker's numeric tower,
 * which is what made that `WindowInsets` overload unreachable.
 */
private fun subsumes(earlier: DeclarationModel, later: DeclarationModel, allowlist: Set<String>): Boolean {
    if (earlier.parameters.size != later.parameters.size) return false
    if (earlier.parameters.map { it.name } != later.parameters.map { it.name }) return false
    return earlier.parameters.indices.all { index ->
        val broad = PythonTypes.render(earlier.parameters[index].type, allowlist).expression.split(" | ").toSet()
        val narrow = PythonTypes.render(later.parameters[index].type, allowlist).expression.split(" | ").toSet()
        narrow.all { n -> broad.any { b -> b == n || (b == "float" && n == "int") || b == "object" || b == "Any" } }
    }
}

/** Dropped, and said so: the declaration is still bound and still in the Kotlin-FQN product, so the
 * note names the table key that reaches it. */
private fun unreachableNote(declaration: DeclarationModel): String =
    "${declaration.bindingName} is unreachable through this signature -- an overload above it accepts " +
        "every call it could. Reach it by its table key."

/**
 * §3.5: Compose's trailing-lambda syntax has no Python equivalent and `Column(modifier, lambda: ...)`
 * reads badly, so a trailing `content` lambda is forced to a keyword. Deliberately narrow -- the
 * measured claim is about `content`, and promoting every trailing lambda would change signatures the
 * document says nothing about.
 */
private fun isKeywordOnly(declaration: DeclarationModel, index: Int): Boolean =
    index == declaration.parameters.lastIndex &&
        declaration.parameters[index].name == "content" &&
        declaration.parameters[index].type.qualifiedName.startsWith("kotlin.Function")

/**
 * §3.6: "the stub's order must be **the same order the Python-side dispatcher resolves in**... The
 * two orders must come from one place in the generator."
 *
 * The dispatcher does not exist (`docs/kotlin-extensions-in-python.md` §6), so rather than leave the
 * order to be written a second time and drift, the generator writes it down as data beside the stub.
 * The list is in the same order the `@overload`s are emitted in, and each element is the
 * `UpcallTable` key the dispatcher would have to call.
 */
private fun renderDispatch(dispatch: Map<String, List<String>>): String = buildString {
    appendLine("{")
    dispatch.entries.forEachIndexed { index, (name, keys) ->
        appendLine("  \"$name\": [")
        keys.forEachIndexed { keyIndex, key ->
            appendLine("    \"$key\"" + if (keyIndex == keys.lastIndex) "" else ",")
        }
        appendLine("  ]" + if (index == dispatch.size - 1) "" else ",")
    }
    appendLine("}")
}
