package org.thisisthepy.python.multiplatform.demo.bindings

/**
 * Android has no boundary shim, so there is nothing for the generated proxy module to be installed
 * over.
 *
 * The *table* is real here and generated by the same processor (`UpcallDemo.android.kt` next
 * door). What is missing is one layer below the proxies: desktop reaches the trampoline through a
 * pair of Panama upcall stubs and iOS through `PyMethodDef`s built by
 * `python.native.ffi.UpcallEntry`, and the JNI path has neither. Nothing in `androidMain` or
 * `artMain` publishes an address Python could call, so `_pm_resolve` and `_pm_invoke` cannot be
 * bound at all -- and [python.multiplatform.ffi.upcall.PythonProxySource]'s entry-point guard
 * refuses to install without them, which is the correct behaviour and the reason this reports
 * rather than raises.
 */
actual fun installPythonProxies(): String =
    "unavailable on Android: no raw upcall entry point is published on the JNI path, so " +
        "_pm_resolve/_pm_invoke cannot be bound and the generated proxy module has nothing to " +
        "call. The generated table itself is installed -- see sections 3 and 4."

/** Not reachable: [installPythonProxies] never installs a proxy on this target. */
actual fun awaitSuspendingDemo(): String =
    "not wired on Android: the proxy module is not installed, so there is no `async def` to await."
