@file:OptIn(kotlin.wasm.ExperimentalWasmInterop::class)

package python.native.ffi.bindings

// GENERATED -- see docs/wasm-design.md and the note in EmbedAPI.wasmJs.kt. Hand edits are fine;
// this file is not regenerated by the build.
//
// Every declaration below is a raw wasm export of `python.wasm`, bound with `@WasmImport` and no
// type adapters -- so a call from Kotlin is a wasm-to-wasm call with no JavaScript frame in it
// (measured at 5.0 ns/call in `wasm-experiment/`). `MODULE` names an ES module that re-exports
// `Module.wasmExports`; see `src/wasmJsMain/resources/cpython.mjs`.
//
// The parameter and return types are NOT transliterated from `EmbedAPI.kt` -- they are read off
// `python.wasm`'s own type section, because `call_indirect`/import type checking is exact and a
// mismatch is a LinkError at instantiation rather than a compile error. The one place the two
// disagree is `Py_ssize_t`: 64 bits on every other target this library builds for, 32 bits on
// wasm32. Fourteen functions are affected and `EmbedAPI.wasmJs.kt` converts at the boundary.

import kotlin.wasm.WasmImport

private const val MODULE = "./cpython.mjs"

@WasmImport(MODULE, "Py_Initialize")
external fun Py_Initialize(): Unit
@WasmImport(MODULE, "Py_InitializeEx")
external fun Py_InitializeEx(initsigs: Int): Unit
@WasmImport(MODULE, "Py_IsInitialized")
external fun Py_IsInitialized(): Int
@WasmImport(MODULE, "Py_IsFinalizing")
external fun Py_IsFinalizing(): Int
@WasmImport(MODULE, "Py_FinalizeEx")
external fun Py_FinalizeEx(): Int
@WasmImport(MODULE, "Py_Finalize")
external fun Py_Finalize(): Unit
@WasmImport(MODULE, "Py_RunMain")
external fun Py_RunMain(): Int
@WasmImport(MODULE, "Py_GetVersion")
external fun Py_GetVersion(): Int
@WasmImport(MODULE, "Py_GetPlatform")
external fun Py_GetPlatform(): Int
@WasmImport(MODULE, "Py_GetCopyright")
external fun Py_GetCopyright(): Int
@WasmImport(MODULE, "Py_GetCompiler")
external fun Py_GetCompiler(): Int
@WasmImport(MODULE, "Py_GetBuildInfo")
external fun Py_GetBuildInfo(): Int
@WasmImport(MODULE, "PyEval_InitThreads")
external fun PyEval_InitThreads(): Unit
@WasmImport(MODULE, "PyThreadState_GetDict")
external fun PyThreadState_GetDict(): Int
@WasmImport(MODULE, "PyGILState_Ensure")
external fun PyGILState_Ensure(): Int
@WasmImport(MODULE, "PyGILState_Release")
external fun PyGILState_Release(state: Int): Unit
@WasmImport(MODULE, "PyGILState_GetThisThreadState")
external fun PyGILState_GetThisThreadState(): Int
@WasmImport(MODULE, "PyEval_SaveThread")
external fun PyEval_SaveThread(): Int
@WasmImport(MODULE, "PyEval_RestoreThread")
external fun PyEval_RestoreThread(tstate: Int): Unit
@WasmImport(MODULE, "PyRun_SimpleString")
external fun PyRun_SimpleString(command: Int): Int
@WasmImport(MODULE, "PyRun_String")
external fun PyRun_String(str: Int, start: Int, globals: Int, locals: Int): Int
@WasmImport(MODULE, "Py_CompileString")
external fun Py_CompileString(str: Int, filename: Int, start: Int): Int
@WasmImport(MODULE, "PyEval_EvalCode")
external fun PyEval_EvalCode(co: Int, globals: Int, locals: Int): Int
@WasmImport(MODULE, "PyErr_Clear")
external fun PyErr_Clear(): Unit
@WasmImport(MODULE, "PyErr_PrintEx")
external fun PyErr_PrintEx(set_sys_last_vars: Int): Unit
@WasmImport(MODULE, "PyErr_Print")
external fun PyErr_Print(): Unit
@WasmImport(MODULE, "PyErr_WriteUnraisable")
external fun PyErr_WriteUnraisable(obj: Int): Unit
@WasmImport(MODULE, "PyErr_DisplayException")
external fun PyErr_DisplayException(exc: Int): Unit
@WasmImport(MODULE, "PyErr_SetString")
external fun PyErr_SetString(type: Int, message: Int): Unit
@WasmImport(MODULE, "PyErr_SetObject")
external fun PyErr_SetObject(type: Int, value: Int): Unit
@WasmImport(MODULE, "PyErr_SetNone")
external fun PyErr_SetNone(type: Int): Unit
@WasmImport(MODULE, "PyErr_BadArgument")
external fun PyErr_BadArgument(): Int
@WasmImport(MODULE, "PyErr_NoMemory")
external fun PyErr_NoMemory(): Int
@WasmImport(MODULE, "PyErr_SetFromErrno")
external fun PyErr_SetFromErrno(type: Int): Int
@WasmImport(MODULE, "PyErr_SetFromErrnoWithFilenameObject")
external fun PyErr_SetFromErrnoWithFilenameObject(type: Int, filenameObject: Int): Int
@WasmImport(MODULE, "PyErr_SetFromErrnoWithFilenameObjects")
external fun PyErr_SetFromErrnoWithFilenameObjects(type: Int, filenameObject: Int, filenameObject2: Int): Int
@WasmImport(MODULE, "PyErr_SetFromErrnoWithFilename")
external fun PyErr_SetFromErrnoWithFilename(type: Int, filename: Int): Int
@WasmImport(MODULE, "PyErr_SetImportError")
external fun PyErr_SetImportError(msg: Int, name: Int, path: Int): Int
@WasmImport(MODULE, "PyErr_SetImportErrorSubclass")
external fun PyErr_SetImportErrorSubclass(exception: Int, msg: Int, name: Int, path: Int): Int
@WasmImport(MODULE, "PyErr_SyntaxLocationEx")
external fun PyErr_SyntaxLocationEx(filename: Int, lineno: Int, col_offset: Int): Unit
@WasmImport(MODULE, "PyErr_SyntaxLocation")
external fun PyErr_SyntaxLocation(filename: Int, lineno: Int): Unit
@WasmImport(MODULE, "PyErr_BadInternalCall")
external fun PyErr_BadInternalCall(): Unit
@WasmImport(MODULE, "PyErr_WarnExplicit")
external fun PyErr_WarnExplicit(category: Int, message: Int, filename: Int, lineno: Int, module: Int, registry: Int): Int
@WasmImport(MODULE, "PyErr_Occurred")
external fun PyErr_Occurred(): Int
@WasmImport(MODULE, "PyErr_ExceptionMatches")
external fun PyErr_ExceptionMatches(exc: Int): Int
@WasmImport(MODULE, "PyErr_GivenExceptionMatches")
external fun PyErr_GivenExceptionMatches(given: Int, exc: Int): Int
@WasmImport(MODULE, "PyErr_GetRaisedException")
external fun PyErr_GetRaisedException(): Int
@WasmImport(MODULE, "PyErr_SetRaisedException")
external fun PyErr_SetRaisedException(exc: Int): Unit
@WasmImport(MODULE, "PyErr_Restore")
external fun PyErr_Restore(type: Int, value: Int, traceback: Int): Unit
@WasmImport(MODULE, "PyErr_GetHandledException")
external fun PyErr_GetHandledException(): Int
@WasmImport(MODULE, "PyErr_SetHandledException")
external fun PyErr_SetHandledException(exc: Int): Unit
@WasmImport(MODULE, "PyErr_SetExcInfo")
external fun PyErr_SetExcInfo(type: Int, value: Int, traceback: Int): Unit
@WasmImport(MODULE, "PyErr_CheckSignals")
external fun PyErr_CheckSignals(): Int
@WasmImport(MODULE, "PyErr_SetInterrupt")
external fun PyErr_SetInterrupt(): Unit
@WasmImport(MODULE, "PyErr_SetInterruptEx")
external fun PyErr_SetInterruptEx(signum: Int): Int
@WasmImport(MODULE, "PyErr_NewException")
external fun PyErr_NewException(name: Int, base: Int, dict: Int): Int
@WasmImport(MODULE, "PyErr_NewExceptionWithDoc")
external fun PyErr_NewExceptionWithDoc(name: Int, doc: Int, base: Int, dict: Int): Int
@WasmImport(MODULE, "PyException_GetTraceback")
external fun PyException_GetTraceback(ex: Int): Int
@WasmImport(MODULE, "PyException_SetTraceback")
external fun PyException_SetTraceback(ex: Int, tb: Int): Int
@WasmImport(MODULE, "PyException_GetContext")
external fun PyException_GetContext(ex: Int): Int
@WasmImport(MODULE, "PyException_SetContext")
external fun PyException_SetContext(ex: Int, ctx: Int): Unit
@WasmImport(MODULE, "PyException_GetCause")
external fun PyException_GetCause(ex: Int): Int
@WasmImport(MODULE, "PyException_SetCause")
external fun PyException_SetCause(ex: Int, cause: Int): Unit
@WasmImport(MODULE, "PyException_GetArgs")
external fun PyException_GetArgs(ex: Int): Int
@WasmImport(MODULE, "PyException_SetArgs")
external fun PyException_SetArgs(ex: Int, args: Int): Unit
@WasmImport(MODULE, "PyUnicodeEncodeError_GetEncoding")
external fun PyUnicodeEncodeError_GetEncoding(exc: Int): Int
@WasmImport(MODULE, "PyUnicodeTranslateError_GetObject")
external fun PyUnicodeTranslateError_GetObject(exc: Int): Int
@WasmImport(MODULE, "PyUnicodeTranslateError_GetReason")
external fun PyUnicodeTranslateError_GetReason(exc: Int): Int
@WasmImport(MODULE, "PyUnicodeTranslateError_SetReason")
external fun PyUnicodeTranslateError_SetReason(exc: Int, reason: Int): Int
@WasmImport(MODULE, "Py_EnterRecursiveCall")
external fun Py_EnterRecursiveCall(where: Int): Int
@WasmImport(MODULE, "Py_LeaveRecursiveCall")
external fun Py_LeaveRecursiveCall(): Unit
@WasmImport(MODULE, "Py_ReprEnter")
external fun Py_ReprEnter(o: Int): Int
@WasmImport(MODULE, "Py_ReprLeave")
external fun Py_ReprLeave(o: Int): Unit
@WasmImport(MODULE, "Py_NewRef")
external fun Py_NewRef(o: Int): Int
@WasmImport(MODULE, "Py_XNewRef")
external fun Py_XNewRef(o: Int): Int
@WasmImport(MODULE, "Py_IncRef")
external fun Py_IncRef(o: Int): Unit
@WasmImport(MODULE, "Py_DecRef")
external fun Py_DecRef(o: Int): Unit
@WasmImport(MODULE, "PyOS_FSPath")
external fun PyOS_FSPath(path: Int): Int
@WasmImport(MODULE, "PySys_GetObject")
external fun PySys_GetObject(name: Int): Int
@WasmImport(MODULE, "PySys_SetObject")
external fun PySys_SetObject(name: Int, v: Int): Int
@WasmImport(MODULE, "PySys_ResetWarnOptions")
external fun PySys_ResetWarnOptions(): Unit
@WasmImport(MODULE, "PySys_GetXOptions")
external fun PySys_GetXOptions(): Int
@WasmImport(MODULE, "PySys_AuditTuple")
external fun PySys_AuditTuple(event: Int, args: Int): Int
@WasmImport(MODULE, "Py_FatalError")
external fun Py_FatalError(message: Int): Unit
@WasmImport(MODULE, "Py_Exit")
external fun Py_Exit(status: Int): Unit
@WasmImport(MODULE, "PyImport_ImportModule")
external fun PyImport_ImportModule(name: Int): Int
@WasmImport(MODULE, "PyImport_ImportModuleNoBlock")
external fun PyImport_ImportModuleNoBlock(name: Int): Int
@WasmImport(MODULE, "PyImport_ImportModuleLevelObject")
external fun PyImport_ImportModuleLevelObject(name: Int, globals: Int, locals: Int, fromlist: Int, level: Int): Int
@WasmImport(MODULE, "PyImport_ImportModuleLevel")
external fun PyImport_ImportModuleLevel(name: Int, globals: Int, locals: Int, fromlist: Int, level: Int): Int
@WasmImport(MODULE, "PyImport_Import")
external fun PyImport_Import(name: Int): Int
@WasmImport(MODULE, "PyImport_ReloadModule")
external fun PyImport_ReloadModule(m: Int): Int
@WasmImport(MODULE, "PyImport_AddModuleRef")
external fun PyImport_AddModuleRef(name: Int): Int
@WasmImport(MODULE, "PyImport_AddModuleObject")
external fun PyImport_AddModuleObject(name: Int): Int
@WasmImport(MODULE, "PyImport_AddModule")
external fun PyImport_AddModule(name: Int): Int
@WasmImport(MODULE, "PyImport_ExecCodeModule")
external fun PyImport_ExecCodeModule(name: Int, co: Int): Int
@WasmImport(MODULE, "PyImport_ExecCodeModuleEx")
external fun PyImport_ExecCodeModuleEx(name: Int, co: Int, pathname: Int): Int
@WasmImport(MODULE, "PyImport_ExecCodeModuleObject")
external fun PyImport_ExecCodeModuleObject(name: Int, co: Int, pathname: Int, cpathname: Int): Int
@WasmImport(MODULE, "PyImport_ExecCodeModuleWithPathnames")
external fun PyImport_ExecCodeModuleWithPathnames(name: Int, co: Int, pathname: Int, cpathname: Int): Int
@WasmImport(MODULE, "PyImport_GetMagicTag")
external fun PyImport_GetMagicTag(): Int
@WasmImport(MODULE, "PyImport_GetModuleDict")
external fun PyImport_GetModuleDict(): Int
@WasmImport(MODULE, "PyImport_GetModule")
external fun PyImport_GetModule(name: Int): Int
@WasmImport(MODULE, "PyImport_GetImporter")
external fun PyImport_GetImporter(path: Int): Int
@WasmImport(MODULE, "PyImport_ImportFrozenModuleObject")
external fun PyImport_ImportFrozenModuleObject(name: Int): Int
@WasmImport(MODULE, "PyImport_ImportFrozenModule")
external fun PyImport_ImportFrozenModule(name: Int): Int
@WasmImport(MODULE, "PyEval_GetBuiltins")
external fun PyEval_GetBuiltins(): Int
@WasmImport(MODULE, "PyEval_GetLocals")
external fun PyEval_GetLocals(): Int
@WasmImport(MODULE, "PyEval_GetGlobals")
external fun PyEval_GetGlobals(): Int
@WasmImport(MODULE, "PyEval_GetFrameBuiltins")
external fun PyEval_GetFrameBuiltins(): Int
@WasmImport(MODULE, "PyEval_GetFrameLocals")
external fun PyEval_GetFrameLocals(): Int
@WasmImport(MODULE, "PyEval_GetFrameGlobals")
external fun PyEval_GetFrameGlobals(): Int
@WasmImport(MODULE, "PyEval_GetFuncName")
external fun PyEval_GetFuncName(func: Int): Int
@WasmImport(MODULE, "PyEval_GetFuncDesc")
external fun PyEval_GetFuncDesc(func: Int): Int
@WasmImport(MODULE, "PyObject_HasAttrWithError")
external fun PyObject_HasAttrWithError(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_HasAttrStringWithError")
external fun PyObject_HasAttrStringWithError(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_HasAttr")
external fun PyObject_HasAttr(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_HasAttrString")
external fun PyObject_HasAttrString(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_GetAttr")
external fun PyObject_GetAttr(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_GetAttrString")
external fun PyObject_GetAttrString(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_GenericGetAttr")
external fun PyObject_GenericGetAttr(o: Int, name: Int): Int
@WasmImport(MODULE, "PyObject_SetAttr")
external fun PyObject_SetAttr(o: Int, attr_name: Int, v: Int): Int
@WasmImport(MODULE, "PyObject_SetAttrString")
external fun PyObject_SetAttrString(o: Int, attr_name: Int, v: Int): Int
@WasmImport(MODULE, "PyObject_GenericSetAttr")
external fun PyObject_GenericSetAttr(o: Int, name: Int, value: Int): Int
@WasmImport(MODULE, "PyObject_DelAttr")
external fun PyObject_DelAttr(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_DelAttrString")
external fun PyObject_DelAttrString(o: Int, attr_name: Int): Int
@WasmImport(MODULE, "PyObject_RichCompare")
external fun PyObject_RichCompare(o1: Int, o2: Int, opid: Int): Int
@WasmImport(MODULE, "PyObject_RichCompareBool")
external fun PyObject_RichCompareBool(o1: Int, o2: Int, opid: Int): Int
@WasmImport(MODULE, "PyObject_Format")
external fun PyObject_Format(obj: Int, format_spec: Int): Int
@WasmImport(MODULE, "PyObject_Repr")
external fun PyObject_Repr(o: Int): Int
@WasmImport(MODULE, "PyObject_ASCII")
external fun PyObject_ASCII(o: Int): Int
@WasmImport(MODULE, "PyObject_Str")
external fun PyObject_Str(o: Int): Int
@WasmImport(MODULE, "PyObject_Bytes")
external fun PyObject_Bytes(o: Int): Int
@WasmImport(MODULE, "PyObject_IsSubclass")
external fun PyObject_IsSubclass(derived: Int, cls: Int): Int
@WasmImport(MODULE, "PyObject_IsInstance")
external fun PyObject_IsInstance(inst: Int, cls: Int): Int
@WasmImport(MODULE, "PyObject_IsTrue")
external fun PyObject_IsTrue(o: Int): Int
@WasmImport(MODULE, "PyObject_Not")
external fun PyObject_Not(o: Int): Int
@WasmImport(MODULE, "PyObject_Type")
external fun PyObject_Type(o: Int): Int
@WasmImport(MODULE, "PyObject_Size")
external fun PyObject_Size(o: Int): Int
@WasmImport(MODULE, "PyObject_Length")
external fun PyObject_Length(o: Int): Int
@WasmImport(MODULE, "PyObject_GetItem")
external fun PyObject_GetItem(o: Int, key: Int): Int
@WasmImport(MODULE, "PyObject_SetItem")
external fun PyObject_SetItem(o: Int, key: Int, v: Int): Int
@WasmImport(MODULE, "PyObject_DelItem")
external fun PyObject_DelItem(o: Int, key: Int): Int
@WasmImport(MODULE, "PyObject_Dir")
external fun PyObject_Dir(o: Int): Int
@WasmImport(MODULE, "PyObject_GetIter")
external fun PyObject_GetIter(o: Int): Int
@WasmImport(MODULE, "PyObject_GetAIter")
external fun PyObject_GetAIter(o: Int): Int
@WasmImport(MODULE, "PyVectorcall_Call")
external fun PyVectorcall_Call(callable: Int, tuple: Int, dict: Int): Int
@WasmImport(MODULE, "PyObject_Call")
external fun PyObject_Call(callable: Int, args: Int, kwargs: Int): Int
@WasmImport(MODULE, "PyObject_CallNoArgs")
external fun PyObject_CallNoArgs(callable: Int): Int
@WasmImport(MODULE, "PyObject_CallObject")
external fun PyObject_CallObject(callable: Int, args: Int): Int
@WasmImport(MODULE, "PyCallable_Check")
external fun PyCallable_Check(o: Int): Int
@WasmImport(MODULE, "PyNumber_Check")
external fun PyNumber_Check(o: Int): Int
@WasmImport(MODULE, "PyNumber_Add")
external fun PyNumber_Add(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Subtract")
external fun PyNumber_Subtract(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Multiply")
external fun PyNumber_Multiply(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_MatrixMultiply")
external fun PyNumber_MatrixMultiply(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_FloorDivide")
external fun PyNumber_FloorDivide(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_TrueDivide")
external fun PyNumber_TrueDivide(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Remainder")
external fun PyNumber_Remainder(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Divmod")
external fun PyNumber_Divmod(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Power")
external fun PyNumber_Power(o1: Int, o2: Int, o3: Int): Int
@WasmImport(MODULE, "PyNumber_Negative")
external fun PyNumber_Negative(o: Int): Int
@WasmImport(MODULE, "PyNumber_Positive")
external fun PyNumber_Positive(o: Int): Int
@WasmImport(MODULE, "PyNumber_Absolute")
external fun PyNumber_Absolute(o: Int): Int
@WasmImport(MODULE, "PyNumber_Invert")
external fun PyNumber_Invert(o: Int): Int
@WasmImport(MODULE, "PyNumber_Lshift")
external fun PyNumber_Lshift(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Rshift")
external fun PyNumber_Rshift(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_And")
external fun PyNumber_And(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Xor")
external fun PyNumber_Xor(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Or")
external fun PyNumber_Or(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceAdd")
external fun PyNumber_InPlaceAdd(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceSubtract")
external fun PyNumber_InPlaceSubtract(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceMultiply")
external fun PyNumber_InPlaceMultiply(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceMatrixMultiply")
external fun PyNumber_InPlaceMatrixMultiply(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceFloorDivide")
external fun PyNumber_InPlaceFloorDivide(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceTrueDivide")
external fun PyNumber_InPlaceTrueDivide(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceRemainder")
external fun PyNumber_InPlaceRemainder(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlacePower")
external fun PyNumber_InPlacePower(o1: Int, o2: Int, o3: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceLshift")
external fun PyNumber_InPlaceLshift(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceRshift")
external fun PyNumber_InPlaceRshift(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceAnd")
external fun PyNumber_InPlaceAnd(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceXor")
external fun PyNumber_InPlaceXor(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_InPlaceOr")
external fun PyNumber_InPlaceOr(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PyNumber_Long")
external fun PyNumber_Long(o: Int): Int
@WasmImport(MODULE, "PyNumber_Float")
external fun PyNumber_Float(o: Int): Int
@WasmImport(MODULE, "PyNumber_Index")
external fun PyNumber_Index(o: Int): Int
@WasmImport(MODULE, "PyNumber_ToBase")
external fun PyNumber_ToBase(n: Int, base: Int): Int
@WasmImport(MODULE, "PyIndex_Check")
external fun PyIndex_Check(o: Int): Int
@WasmImport(MODULE, "PySequence_Check")
external fun PySequence_Check(o: Int): Int
@WasmImport(MODULE, "PySequence_Concat")
external fun PySequence_Concat(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PySequence_InPlaceConcat")
external fun PySequence_InPlaceConcat(o1: Int, o2: Int): Int
@WasmImport(MODULE, "PySequence_Contains")
external fun PySequence_Contains(o: Int, value: Int): Int
@WasmImport(MODULE, "PySequence_List")
external fun PySequence_List(o: Int): Int
@WasmImport(MODULE, "PySequence_Tuple")
external fun PySequence_Tuple(o: Int): Int
@WasmImport(MODULE, "PySequence_Fast")
external fun PySequence_Fast(o: Int, m: Int): Int
@WasmImport(MODULE, "PyMapping_Check")
external fun PyMapping_Check(o: Int): Int
@WasmImport(MODULE, "PyMapping_GetItemString")
external fun PyMapping_GetItemString(o: Int, key: Int): Int
@WasmImport(MODULE, "PyMapping_SetItemString")
external fun PyMapping_SetItemString(o: Int, key: Int, v: Int): Int
@WasmImport(MODULE, "PyMapping_HasKeyWithError")
external fun PyMapping_HasKeyWithError(o: Int, key: Int): Int
@WasmImport(MODULE, "PyMapping_HasKeyStringWithError")
external fun PyMapping_HasKeyStringWithError(o: Int, key: Int): Int
@WasmImport(MODULE, "PyMapping_HasKey")
external fun PyMapping_HasKey(o: Int, key: Int): Int
@WasmImport(MODULE, "PyMapping_HasKeyString")
external fun PyMapping_HasKeyString(o: Int, key: Int): Int
@WasmImport(MODULE, "PyMapping_Keys")
external fun PyMapping_Keys(o: Int): Int
@WasmImport(MODULE, "PyMapping_Values")
external fun PyMapping_Values(o: Int): Int
@WasmImport(MODULE, "PyMapping_Items")
external fun PyMapping_Items(o: Int): Int
@WasmImport(MODULE, "PyIter_Check")
external fun PyIter_Check(o: Int): Int
@WasmImport(MODULE, "PyAIter_Check")
external fun PyAIter_Check(o: Int): Int
@WasmImport(MODULE, "PyIter_Next")
external fun PyIter_Next(o: Int): Int
@WasmImport(MODULE, "PyLong_FromLongLong")
external fun PyLong_FromLongLong(v: Long): Int
@WasmImport(MODULE, "PyLong_FromDouble")
external fun PyLong_FromDouble(v: Double): Int
@WasmImport(MODULE, "PyLong_AsInt")
external fun PyLong_AsInt(obj: Int): Int
@WasmImport(MODULE, "PyLong_AsLongLong")
external fun PyLong_AsLongLong(obj: Int): Long
@WasmImport(MODULE, "PyLong_AsDouble")
external fun PyLong_AsDouble(pylong: Int): Double
@WasmImport(MODULE, "PyLong_GetInfo")
external fun PyLong_GetInfo(): Int
@WasmImport(MODULE, "PyBool_FromLong")
external fun PyBool_FromLong(v: Int): Int
@WasmImport(MODULE, "PyFloat_FromString")
external fun PyFloat_FromString(str: Int): Int
@WasmImport(MODULE, "PyFloat_FromDouble")
external fun PyFloat_FromDouble(v: Double): Int
@WasmImport(MODULE, "PyFloat_AsDouble")
external fun PyFloat_AsDouble(pyfloat: Int): Double
@WasmImport(MODULE, "PyFloat_GetInfo")
external fun PyFloat_GetInfo(): Int
@WasmImport(MODULE, "PyFloat_GetMax")
external fun PyFloat_GetMax(): Double
@WasmImport(MODULE, "PyFloat_GetMin")
external fun PyFloat_GetMin(): Double
@WasmImport(MODULE, "PyBytes_FromString")
external fun PyBytes_FromString(v: Int): Int
@WasmImport(MODULE, "PyBytes_FromObject")
external fun PyBytes_FromObject(o: Int): Int
@WasmImport(MODULE, "PyBytes_AsString")
external fun PyBytes_AsString(o: Int): Int
@WasmImport(MODULE, "PyByteArray_FromObject")
external fun PyByteArray_FromObject(o: Int): Int
@WasmImport(MODULE, "PyByteArray_Concat")
external fun PyByteArray_Concat(a: Int, b: Int): Int
@WasmImport(MODULE, "PyByteArray_AsString")
external fun PyByteArray_AsString(bytearray: Int): Int
@WasmImport(MODULE, "PyUnicode_IsIdentifier")
external fun PyUnicode_IsIdentifier(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_FromString")
external fun PyUnicode_FromString(str: Int): Int
@WasmImport(MODULE, "PyUnicode_FromObject")
external fun PyUnicode_FromObject(obj: Int): Int
@WasmImport(MODULE, "PyUnicode_FromEncodedObject")
external fun PyUnicode_FromEncodedObject(obj: Int, encoding: Int, errors: Int): Int
@WasmImport(MODULE, "PyUnicode_DecodeLocale")
external fun PyUnicode_DecodeLocale(str: Int, errors: Int): Int
@WasmImport(MODULE, "PyUnicode_EncodeLocale")
external fun PyUnicode_EncodeLocale(unicode: Int, errors: Int): Int
@WasmImport(MODULE, "PyUnicode_DecodeFSDefault")
external fun PyUnicode_DecodeFSDefault(str: Int): Int
@WasmImport(MODULE, "PyUnicode_EncodeFSDefault")
external fun PyUnicode_EncodeFSDefault(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsEncodedString")
external fun PyUnicode_AsEncodedString(unicode: Int, encoding: Int, errors: Int): Int
@WasmImport(MODULE, "PyUnicode_AsUTF8String")
external fun PyUnicode_AsUTF8String(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsUTF8")
external fun PyUnicode_AsUTF8(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsUTF32String")
external fun PyUnicode_AsUTF32String(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsUTF16String")
external fun PyUnicode_AsUTF16String(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsUnicodeEscapeString")
external fun PyUnicode_AsUnicodeEscapeString(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsRawUnicodeEscapeString")
external fun PyUnicode_AsRawUnicodeEscapeString(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsLatin1String")
external fun PyUnicode_AsLatin1String(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsASCIIString")
external fun PyUnicode_AsASCIIString(unicode: Int): Int
@WasmImport(MODULE, "PyUnicode_AsCharmapString")
external fun PyUnicode_AsCharmapString(unicode: Int, mapping: Int): Int
@WasmImport(MODULE, "PyUnicode_Translate")
external fun PyUnicode_Translate(unicode: Int, table: Int, errors: Int): Int
@WasmImport(MODULE, "PyUnicode_Concat")
external fun PyUnicode_Concat(left: Int, right: Int): Int
@WasmImport(MODULE, "PyUnicode_Splitlines")
external fun PyUnicode_Splitlines(unicode: Int, keepends: Int): Int
@WasmImport(MODULE, "PyUnicode_Join")
external fun PyUnicode_Join(separator: Int, seq: Int): Int
@WasmImport(MODULE, "PyUnicode_Compare")
external fun PyUnicode_Compare(left: Int, right: Int): Int
@WasmImport(MODULE, "PyUnicode_EqualToUTF8")
external fun PyUnicode_EqualToUTF8(unicode: Int, string: Int): Int
@WasmImport(MODULE, "PyUnicode_CompareWithASCIIString")
external fun PyUnicode_CompareWithASCIIString(unicode: Int, string: Int): Int
@WasmImport(MODULE, "PyUnicode_RichCompare")
external fun PyUnicode_RichCompare(left: Int, right: Int, op: Int): Int
@WasmImport(MODULE, "PyUnicode_Format")
external fun PyUnicode_Format(format: Int, args: Int): Int
@WasmImport(MODULE, "PyUnicode_Contains")
external fun PyUnicode_Contains(unicode: Int, substr: Int): Int
@WasmImport(MODULE, "PyUnicode_InternFromString")
external fun PyUnicode_InternFromString(str: Int): Int
@WasmImport(MODULE, "PyList_New")
external fun PyList_New(len: Int): Int
@WasmImport(MODULE, "PyList_Size")
external fun PyList_Size(list: Int): Int
@WasmImport(MODULE, "PyList_GetItem")
external fun PyList_GetItem(list: Int, index: Int): Int
@WasmImport(MODULE, "PyList_SetItem")
external fun PyList_SetItem(list: Int, index: Int, item: Int): Int
@WasmImport(MODULE, "PyList_Insert")
external fun PyList_Insert(list: Int, index: Int, item: Int): Int
@WasmImport(MODULE, "PyList_Append")
external fun PyList_Append(list: Int, item: Int): Int
@WasmImport(MODULE, "PyList_Sort")
external fun PyList_Sort(list: Int): Int
@WasmImport(MODULE, "PyList_Reverse")
external fun PyList_Reverse(list: Int): Int
@WasmImport(MODULE, "PyList_AsTuple")
external fun PyList_AsTuple(list: Int): Int
@WasmImport(MODULE, "PyDict_New")
external fun PyDict_New(): Int
@WasmImport(MODULE, "PyDict_Size")
external fun PyDict_Size(p: Int): Int
@WasmImport(MODULE, "PyDictProxy_New")
external fun PyDictProxy_New(mapping: Int): Int
@WasmImport(MODULE, "PyDict_Clear")
external fun PyDict_Clear(p: Int): Unit
@WasmImport(MODULE, "PyDict_Contains")
external fun PyDict_Contains(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_Copy")
external fun PyDict_Copy(p: Int): Int
@WasmImport(MODULE, "PyDict_SetItem")
external fun PyDict_SetItem(p: Int, key: Int, v: Int): Int
@WasmImport(MODULE, "PyDict_SetItemString")
external fun PyDict_SetItemString(p: Int, key: Int, v: Int): Int
@WasmImport(MODULE, "PyDict_DelItem")
external fun PyDict_DelItem(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_DelItemString")
external fun PyDict_DelItemString(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_GetItem")
external fun PyDict_GetItem(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_GetItemWithError")
external fun PyDict_GetItemWithError(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_GetItemString")
external fun PyDict_GetItemString(p: Int, key: Int): Int
@WasmImport(MODULE, "PyDict_Items")
external fun PyDict_Items(p: Int): Int
@WasmImport(MODULE, "PyDict_Keys")
external fun PyDict_Keys(p: Int): Int
@WasmImport(MODULE, "PyDict_Values")
external fun PyDict_Values(p: Int): Int
@WasmImport(MODULE, "PyDict_Merge")
external fun PyDict_Merge(a: Int, b: Int, override: Int): Int
@WasmImport(MODULE, "PyDict_Update")
external fun PyDict_Update(a: Int, b: Int): Int
@WasmImport(MODULE, "PyDict_MergeFromSeq2")
external fun PyDict_MergeFromSeq2(a: Int, seq2: Int, override: Int): Int
@WasmImport(MODULE, "PySet_New")
external fun PySet_New(iterable: Int): Int
@WasmImport(MODULE, "PyFrozenSet_New")
external fun PyFrozenSet_New(iterable: Int): Int
@WasmImport(MODULE, "PySet_Contains")
external fun PySet_Contains(anyset: Int, key: Int): Int
@WasmImport(MODULE, "PySet_Size")
external fun PySet_Size(anyset: Int): Int
@WasmImport(MODULE, "PySet_Add")
external fun PySet_Add(set: Int, key: Int): Int
@WasmImport(MODULE, "PySet_Discard")
external fun PySet_Discard(set: Int, key: Int): Int
@WasmImport(MODULE, "PySet_Pop")
external fun PySet_Pop(set: Int): Int
@WasmImport(MODULE, "PySet_Clear")
external fun PySet_Clear(set: Int): Int
@WasmImport(MODULE, "PySeqIter_New")
external fun PySeqIter_New(seq: Int): Int
@WasmImport(MODULE, "PyCallIter_New")
external fun PyCallIter_New(callable: Int, sentinel: Int): Int
@WasmImport(MODULE, "PyWeakref_NewRef")
external fun PyWeakref_NewRef(ob: Int, callback: Int): Int
@WasmImport(MODULE, "PyWeakref_NewProxy")
external fun PyWeakref_NewProxy(ob: Int, callback: Int): Int
@WasmImport(MODULE, "PyWeakref_GetObject")
external fun PyWeakref_GetObject(ref: Int): Int
@WasmImport(MODULE, "PyObject_ClearWeakRefs")
external fun PyObject_ClearWeakRefs(o: Int): Unit
@WasmImport(MODULE, "PyType_IsSubtype")
external fun PyType_IsSubtype(a: Int, b: Int): Int
@WasmImport(MODULE, "PyType_Ready")
external fun PyType_Ready(type: Int): Int
@WasmImport(MODULE, "PyType_GetName")
external fun PyType_GetName(type: Int): Int
@WasmImport(MODULE, "PyType_GetFullyQualifiedName")
external fun PyType_GetFullyQualifiedName(type: Int): Int
@WasmImport(MODULE, "PyType_GetModuleName")
external fun PyType_GetModuleName(type: Int): Int
@WasmImport(MODULE, "PyType_GetModule")
external fun PyType_GetModule(type: Int): Int
@WasmImport(MODULE, "PyTuple_New")
external fun PyTuple_New(len: Int): Int
@WasmImport(MODULE, "PyTuple_Size")
external fun PyTuple_Size(p: Int): Int
@WasmImport(MODULE, "PyTuple_GetItem")
external fun PyTuple_GetItem(p: Int, pos: Int): Int
@WasmImport(MODULE, "PyTuple_GetSlice")
external fun PyTuple_GetSlice(p: Int, low: Int, high: Int): Int
@WasmImport(MODULE, "PyTuple_SetItem")
external fun PyTuple_SetItem(p: Int, pos: Int, o: Int): Int
@WasmImport(MODULE, "PyModule_GetName")
external fun PyModule_GetName(module: Int): Int
@WasmImport(MODULE, "PyModule_GetDict")
external fun PyModule_GetDict(module: Int): Int
@WasmImport(MODULE, "PyModule_GetFilenameObject")
external fun PyModule_GetFilenameObject(module: Int): Int

// The C allocator, not `PyMem_*`: Kotlin must be able to stage a C string before it holds the GIL,
// and `PyMem_Malloc` requires an attached thread state. This is also the only allocation path that
// exists here -- `withScopedMemoryAllocator` must never be called on this target, because it
// allocates from address 0 upward, directly on top of Emscripten's static data. CPython allocates;
// Kotlin only dereferences addresses it was handed.
@WasmImport(MODULE, "malloc")
external fun malloc(size: Int): Int

@WasmImport(MODULE, "free")
external fun free(ptr: Int)


// -------------------------------------------------------------------------------------------------
// The type-construction surface, for `ProxyTypeFactory` (ROADMAP §7 and §10)
//
// These are not in `EmbedAPI.kt` -- no `expect` declares them, because each platform's proxy type
// factory reaches them its own way (desktop through a `MethodHandle`, Android through
// `RegisterNatives`). All four are stable-ABI functions.
// -------------------------------------------------------------------------------------------------

@WasmImport(MODULE, "PyType_FromSpec")
external fun PyType_FromSpec(spec: Int): Int

/** `void *PyObject_GetTypeData(PyObject *o, PyTypeObject *cls)` -- where the handle is kept. */
@WasmImport(MODULE, "PyObject_GetTypeData")
external fun PyObject_GetTypeData(obj: Int, type: Int): Int

/** `void *PyType_GetSlot(PyTypeObject *type, int slot)` -- the only abi3 route to `tp_free`. */
@WasmImport(MODULE, "PyType_GetSlot")
external fun PyType_GetSlot(type: Int, slot: Int): Int

@WasmImport(MODULE, "PyObject_GC_UnTrack")
external fun PyObject_GC_UnTrack(op: Int)

// -------------------------------------------------------------------------------------------------
// The glue, and why it is here rather than in `python.wasm`
//
// These three are the *only* declarations in this file that are not CPython exports; they are
// JavaScript functions in `src/wasmJsMain/resources/cpython.mjs`. Each exists because of something
// Kotlin/Wasm cannot express, not because a JS hop was wanted:
//
//   * a table index cannot be obtained from inside Kotlin, so installing a `@WasmExport` into
//     CPython's `__indirect_function_table` has to happen from JS (`pmpRegisterUpcall`);
//   * Kotlin/Wasm has no `call_indirect` primitive, so calling a C function *pointer* -- which is
//     what `visitproc` and `tp_free` are -- has to go through `WebAssembly.Table.get`
//     (`pmpCallVisit`, `pmpCallFree`).
//
// All three are cold: registration runs three times per process, and the other two run inside a
// cyclic collection or a proxy's deallocation. Nothing on the ordinary downcall path touches
// JavaScript, and nothing in the *upcall* path does either -- CPython reaches the Kotlin export
// through `call_indirect`, measured at 3.1 ns in `wasm-experiment/`.
//
// `verifyWasmAbiSignatures` knows these are glue: it checks that `cpython.mjs` really exports them,
// and does not look for them in `python.wasm`.
// -------------------------------------------------------------------------------------------------

/**
 * Installs the Kotlin `@WasmExport` named by the NUL-terminated C string at [namePtr] into
 * CPython's `__indirect_function_table` and returns its index -- which *is* the C function pointer.
 * Returns a negative value if there is no such export or if the table refused to grow.
 */
@WasmImport(MODULE, "pmpRegisterUpcall")
external fun pmpRegisterUpcall(namePtr: Int): Int

/** `visit(obj, arg)`, where `visit` is the `visitproc` at table index [fp]. */
@WasmImport(MODULE, "pmpCallVisit")
external fun pmpCallVisit(fp: Int, obj: Int, arg: Int): Int

/** `free(obj)`, where `free` is the `freefunc` at table index [fp]. */
@WasmImport(MODULE, "pmpCallFree")
external fun pmpCallFree(fp: Int, obj: Int)
